"""
Run an interactive AURORA map of all Gaia DR3 microlensing events.

The application uses the Hammer sky image generated by aurora_sky_render.py,
reads the existing AURORA FITS catalogue, and serves a dependency-free local
web interface with smooth zooming, hover previews, full event cards, a
Paczynski light curve, and a conceptual third-person lensing view.

Examples
--------
    python microlensing/aurora_microlensing_map.py
    python microlensing/aurora_microlensing_map.py --no-browser --port 8765
    python microlensing/aurora_microlensing_map.py \
        --map maps/aurora_sky_map_hammer_16k.png
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import math
import mimetypes
import sys
import threading
import webbrowser
from collections import Counter
from datetime import timezone
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import unquote, urlsplit

import numpy as np
from astropy.table import Table
from astropy.time import Time

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from core.aurora_console import console
from core.aurora_memory import MemoryController
from core.aurora_render_core import star_colors_from_columns
from core.aurora_paths import asset_path, map_path
from core.aurora_resolution import get_resolution

DEFAULT_CATALOG = asset_path("aurora_microlensing.fits")
DEFAULT_SERVER_HOST = "127.0.0.1"
DEFAULT_SERVER_PORT = 0
SKY_MAP_NAME = get_resolution(16).hammer_map_name
GAIA_TIME_ZERO_JD = 2_455_197.5
SPEED_OF_LIGHT_M_S = 299_792_458.0
GRAVITATIONAL_CONSTANT = 6.67430e-11
SOLAR_MASS_KG = 1.98847e30
PARSEC_M = 3.085677581491367e16
ASSUMED_LENS_DISTANCE_FRACTION = 0.5
ASSUMED_TRANSVERSE_SPEED_KMS = 100.0
MASS_SCENARIO_SPEED_RANGE_KMS = (50.0, 200.0)
MASS_SCENARIO_DISTANCE_FRACTION_RANGE = (0.25, 0.75)
LENS_MASS_RANGES = (
    ("free-floating-planet", "Planeta swobodna", 1e-6, 0.013),
    ("neutron-star", "Gwiazda neutronowa", 1.0, 2.5),
    ("black-hole", "Czarna dziura", 2.5, 120.0),
)
MEMORY = MemoryController.from_environment()


def _finite(value, default=None):
    """Return a JSON-safe scalar or a default for masked/non-finite values."""
    if np.ma.is_masked(value):
        return default
    try:
        number = float(value)
    except (TypeError, ValueError):
        return default
    return number if math.isfinite(number) else default


def _first_finite(row, names):
    for name in names:
        if name in row.colnames:
            value = _finite(row[name])
            if value is not None:
                return value, name
    return None, None


def _temperature_from_row(row):
    temperature = _finite(row["teff_gspphot"]) if "teff_gspphot" in row.colnames else None
    if temperature is not None:
        return temperature, "Gaia teff_gspphot"

    colour = _finite(row["bp_rp"]) if "bp_rp" in row.colnames else None
    if colour is not None:
        colour = min(4.0, max(-0.5, colour))
        temperature = 4600.0 * (
            1.0 / (0.92 * colour + 1.7)
            + 1.0 / (0.92 * colour + 0.62)
        )
        return temperature, "oszacowanie z BP−RP"
    return None, None


def _source_colour_from_row(row):
    teff = _finite(row["teff_gspphot"]) if "teff_gspphot" in row.colnames else None
    bp_rp = _finite(row["bp_rp"]) if "bp_rp" in row.colnames else None
    rgb = star_colors_from_columns(
        np.array([np.nan if teff is None else teff], dtype=np.float32),
        np.array([np.nan if bp_rp is None else bp_rp], dtype=np.float32),
    )[0]
    rgb = np.clip(np.asarray(rgb, dtype=np.float32), 0.0, 1.0)
    rgb255 = tuple(int(round(float(channel) * 255.0)) for channel in rgb)
    return {
        "rgb": [round(float(channel), 4) for channel in rgb],
        "css": f"rgb({rgb255[0]}, {rgb255[1]}, {rgb255[2]})",
        "hex": f"#{rgb255[0]:02x}{rgb255[1]:02x}{rgb255[2]:02x}",
    }


def _spectral_description(temperature):
    if temperature is None:
        return "Gwiazda źródłowa — typ widmowy nieustalony"
    if temperature >= 30_000:
        spectral = "O"
    elif temperature >= 10_000:
        spectral = "B"
    elif temperature >= 7_500:
        spectral = "A"
    elif temperature >= 6_000:
        spectral = "F"
    elif temperature >= 5_200:
        spectral = "G"
    elif temperature >= 3_700:
        spectral = "K"
    else:
        spectral = "M"
    return f"Gwiazda źródłowa — przybliżony typ {spectral}"


def _hammer_position(longitude_deg, latitude_deg):
    """Return normalized pixels matching aurora_sky_render.py."""
    longitude = longitude_deg
    if longitude > 180.0:
        longitude -= 360.0
    longitude = -math.radians(longitude)
    latitude = math.radians(latitude_deg)

    cos_b = math.cos(latitude)
    half_l = longitude * 0.5
    z = math.sqrt(1.0 + cos_b * math.cos(half_l))
    x_hammer = 2.0 * math.sqrt(2.0) * cos_b * math.sin(half_l) / z
    y_hammer = math.sqrt(2.0) * math.sin(latitude) / z
    x = (x_hammer / (2.0 * math.sqrt(2.0)) + 1.0) * 0.5
    y = (1.0 - y_hammer / math.sqrt(2.0)) * 0.5
    return x, y


def _maximum_amplification(u0):
    u2 = max(u0 * u0, np.finfo(np.float64).tiny)
    return (u2 + 2.0) / math.sqrt(u2 * (u2 + 4.0))


def _gaia_date(tmax):
    """Convert Gaia DR3 BJD(TCB)-2455197.5 to an approximate UTC date."""
    time_tcb = Time(tmax + GAIA_TIME_ZERO_JD, format="jd", scale="tcb")
    utc = time_tcb.utc.to_datetime(timezone=timezone.utc)
    return {
        "iso": utc.isoformat().replace("+00:00", "Z"),
        "date": utc.strftime("%Y-%m-%d"),
        "label": utc.strftime("%d.%m.%Y"),
        "bjd": tmax + GAIA_TIME_ZERO_JD,
    }


def _estimate_lens_mass(
    timescale_days,
    source_distance_pc,
    *,
    lens_distance_fraction=ASSUMED_LENS_DISTANCE_FRACTION,
    transverse_speed_kms=ASSUMED_TRANSVERSE_SPEED_KMS,
):
    """Estimate lens mass from tE under an explicit thin-lens geometry."""
    if (
        timescale_days is None
        or timescale_days <= 0.0
        or source_distance_pc is None
        or source_distance_pc <= 0.0
        or not 0.0 < lens_distance_fraction < 1.0
        or transverse_speed_kms <= 0.0
    ):
        return None

    source_distance_m = source_distance_pc * PARSEC_M
    lens_distance_m = source_distance_m * lens_distance_fraction
    lens_source_distance_m = source_distance_m - lens_distance_m
    transverse_speed_m_s = transverse_speed_kms * 1000.0
    einstein_crossing_s = timescale_days * 86_400.0
    einstein_radius_m = transverse_speed_m_s * einstein_crossing_s
    geometry = source_distance_m / (
        lens_distance_m * lens_source_distance_m
    )
    mass_kg = (
        SPEED_OF_LIGHT_M_S**2
        * einstein_radius_m**2
        * geometry
        / (4.0 * GRAVITATIONAL_CONSTANT)
    )
    mass_solar = mass_kg / SOLAR_MASS_KG
    return mass_solar if math.isfinite(mass_solar) and mass_solar > 0.0 else None


def _mass_scenario_range(timescale_days, source_distance_pc):
    """Return a sensitivity envelope, not a statistical confidence interval."""
    low_speed, high_speed = MASS_SCENARIO_SPEED_RANGE_KMS
    low_fraction, high_fraction = MASS_SCENARIO_DISTANCE_FRACTION_RANGE
    values = [
        _estimate_lens_mass(
            timescale_days,
            source_distance_pc,
            lens_distance_fraction=fraction,
            transverse_speed_kms=speed,
        )
        for speed in (low_speed, high_speed)
        for fraction in (
            low_fraction,
            ASSUMED_LENS_DISTANCE_FRACTION,
            high_fraction,
        )
    ]
    values = [value for value in values if value is not None]
    return (min(values), max(values)) if values else (None, None)


def _lens_mass_regime(lens_mass):
    if lens_mass is None or lens_mass <= 0.0:
        return {
            "label": None,
            "key": None,
            "note": "Brak masy pozwalającej porównać scenariusz z zakresami referencyjnymi.",
            "categories": [
                {"key": key, "label": label, "low": low, "high": high, "inRange": False}
                for key, label, low, high in LENS_MASS_RANGES
            ],
        }

    categories = [
        {
            "key": key,
            "label": label,
            "low": low,
            "high": high,
            "inRange": low <= lens_mass <= high,
        }
        for key, label, low, high in LENS_MASS_RANGES
    ]
    match = next((category for category in categories if category["inRange"]), None)
    if match:
        note = (
            f"Wartość {lens_mass:.3g} M☉ mieści się w przyjętym zakresie "
            f"referencyjnym „{match['label']}”. To zgodność zakresu masy, "
            "a nie identyfikacja obiektu."
        )
    else:
        note = (
            f"Wartość {lens_mass:.3g} M☉ nie mieści się w żadnym z trzech "
            "wyróżnionych zakresów referencyjnych."
        )

    return {
        "label": match["label"] if match else None,
        "key": match["key"] if match else None,
        "note": note,
        "categories": categories,
    }


def load_event_payload(catalog_path):
    console.print(f"  → Reading event catalogue: {catalog_path}")
    table = Table.read(catalog_path)
    required = {"source_id", "l", "b", "paczynski0_tmax", "paczynski0_te", "paczynski0_u0"}
    missing = sorted(required - set(table.colnames))
    if missing:
        raise KeyError(f"Missing FITS columns: {', '.join(missing)}")

    events = []
    rejected = Counter()
    seen_source_ids = set()
    for row in table:
        longitude = _finite(row["l"])
        latitude = _finite(row["b"])
        tmax = _finite(row["paczynski0_tmax"])
        timescale = _finite(row["paczynski0_te"])
        impact = _finite(row["paczynski0_u0"])
        if (
            longitude is None
            or latitude is None
            or tmax is None
            or timescale is None
            or impact is None
        ):
            rejected["brak wymaganych parametrów"] += 1
            continue
        if not 0.0 <= longitude <= 360.0 or not -90.0 <= latitude <= 90.0:
            rejected["współrzędne poza zakresem"] += 1
            continue
        if timescale <= 0.0:
            rejected["niedodatni czas tE"] += 1
            continue

        try:
            source_id = str(int(row["source_id"]))
        except (TypeError, ValueError, OverflowError):
            rejected["nieprawidłowe source_id"] += 1
            continue
        if source_id in seen_source_ids:
            rejected["duplikat source_id"] += 1
            continue
        seen_source_ids.add(source_id)
        impact = abs(impact)

        x, y = _hammer_position(longitude, latitude)
        date = _gaia_date(tmax)
        parallax = _finite(row["parallax"]) if "parallax" in table.colnames else None
        parallax_error = (
            _finite(row["parallax_error"])
            if "parallax_error" in table.colnames
            else None
        )
        if parallax is not None and parallax <= 0.0:
            parallax = None
        if parallax_error is not None and parallax_error <= 0.0:
            parallax_error = None
        distance_pc = 1000.0 / parallax if parallax is not None and parallax > 0.0 else None
        parallax_relative_error = (
            parallax_error / parallax
            if parallax is not None and parallax_error is not None
            else None
        )
        distance_low_pc = (
            1000.0 / (parallax + parallax_error)
            if parallax is not None and parallax_error is not None
            else None
        )
        distance_high_pc = (
            1000.0 / (parallax - parallax_error)
            if (
                parallax is not None
                and parallax_error is not None
                and parallax > parallax_error
            )
            else None
        )
        temperature, temperature_origin = _temperature_from_row(row)
        source_colour = _source_colour_from_row(row)
        catalog_lens_mass, mass_column = _first_finite(
            row,
            ("paczynski0_mass", "paczynski_mass", "lens_mass", "mass"),
        )
        if catalog_lens_mass is not None and catalog_lens_mass <= 0.0:
            catalog_lens_mass = None
            mass_column = None
        model_lens_mass = (
            _estimate_lens_mass(timescale, distance_pc)
            if catalog_lens_mass is None
            else None
        )
        lens_mass = catalog_lens_mass if catalog_lens_mass is not None else model_lens_mass
        mass_status = (
            "catalog"
            if catalog_lens_mass is not None
            else "model"
            if model_lens_mass is not None
            else "missing"
        )
        model_mass_low, model_mass_high = (
            _mass_scenario_range(timescale, distance_pc)
            if model_lens_mass is not None
            else (None, None)
        )
        lens_kind = None
        lens_kind_column = None
        for name in ("lens_type", "lens_class", "lens_object"):
            if name in table.colnames and not np.ma.is_masked(row[name]):
                text = str(row[name]).strip()
                if text:
                    lens_kind = text
                    lens_kind_column = name
                    break
        lens_regime = _lens_mass_regime(lens_mass)
        g_mag = _finite(row["phot_g_mean_mag"]) if "phot_g_mean_mag" in table.colnames else None
        if g_mag is not None and not -5.0 <= g_mag <= 40.0:
            g_mag = None
        bp_rp = _finite(row["bp_rp"]) if "bp_rp" in table.colnames else None
        if bp_rp is not None and not -5.0 <= bp_rp <= 15.0:
            bp_rp = None

        events.append(
            {
                "key": source_id,
                "sourceId": source_id,
                "l": longitude,
                "b": latitude,
                "x": x,
                "y": y,
                "tmax": tmax,
                "date": date,
                "te": timescale,
                "u0": impact,
                "aMax": _maximum_amplification(impact),
                "gMag": g_mag,
                "bpRp": bp_rp,
                "temperature": temperature,
                "temperatureOrigin": temperature_origin,
                "sourceColor": source_colour,
                "sourceDescription": _spectral_description(temperature),
                "parallax": parallax,
                "parallaxError": parallax_error,
                "parallaxRelativeError": parallax_relative_error,
                "distancePc": distance_pc,
                "distanceLowPc": distance_low_pc,
                "distanceHighPc": distance_high_pc,
                "distanceMethod": "odwrotność paralaksy bez korekty punktu zerowego",
                "catalogLensMass": catalog_lens_mass,
                "modelLensMass": model_lens_mass,
                "lensMass": lens_mass,
                "massOrigin": mass_column,
                "massStatus": mass_status,
                "massIsEstimated": mass_status == "model",
                "modelMassLow": model_mass_low,
                "modelMassHigh": model_mass_high,
                "modelDefaults": {
                    "transverseSpeedKms": ASSUMED_TRANSVERSE_SPEED_KMS,
                    "lensDistanceFraction": ASSUMED_LENS_DISTANCE_FRACTION,
                },
                "massEstimateNote": (
                    "Hipoteza modelowa, nie pomiar: wynik zależy od nieznanej "
                    "odległości soczewki i względnej prędkości poprzecznej."
                    if mass_status == "model"
                    else None
                ),
                "lensKind": lens_kind,
                "lensKindOrigin": lens_kind_column,
                "lensHypothesis": lens_regime["label"],
                "lensCategory": lens_regime["key"],
                "lensInferenceNote": lens_regime["note"],
                "lensCategories": lens_regime["categories"],
            }
        )

    events.sort(key=lambda event: event["tmax"])
    for index, event in enumerate(events, start=1):
        event["catalogIndex"] = index
        event["name"] = f"AUR–ML–{index:03d}"

    if not events:
        raise RuntimeError("No valid microlensing events remain after filtering")

    durations = np.asarray([event["te"] for event in events], dtype=float)
    amplifications = np.asarray([event["aMax"] for event in events], dtype=float)
    payload = {
        "meta": {
            "count": len(events),
            "dateStart": events[0]["date"]["date"],
            "dateEnd": events[-1]["date"]["date"],
            "medianTimescale": float(np.median(durations)),
            "strongCount": int(np.count_nonzero(amplifications >= 2.0)),
            "massKnownCount": sum(event["massStatus"] == "catalog" for event in events),
            "massModelCount": sum(event["massStatus"] == "model" for event in events),
            "inputCount": len(table),
            "filteredOutCount": sum(rejected.values()),
            "rejectionReasons": dict(rejected),
            "parallaxErrorCount": sum(event["parallaxError"] is not None for event in events),
            "projection": "Hammer, współrzędne galaktyczne",
            "catalog": catalog_path.name,
            "timeReference": "BJD(TCB) − 2455197.5",
        },
        "events": events,
    }
    console.print(f"  ✓ Prepared {len(events):,} valid events")
    return payload


def find_sky_map(explicit_path=None):
    if explicit_path:
        path = Path(explicit_path).expanduser().resolve()
        if path.is_file():
            return path
        raise FileNotFoundError(f"Sky map does not exist: {path}")

    candidates = [map_path(SKY_MAP_NAME)]
    for candidate in candidates:
        if candidate.is_file():
            return candidate.resolve()
    checked = "\n".join(f"    - {path}" for path in candidates)
    raise FileNotFoundError(
        "The Hammer sky map has not been generated yet.\n"
        "Run main/aurora_sky_render.py first, or use --map PATH.\n"
        f"Checked:\n{checked}"
    )


APP_HTML = r"""<!doctype html>
<html lang="pl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="theme-color" content="#050608">
  <title>AURORA — Atlas mikrosoczewkowania</title>
  <style>
    :root {
      color-scheme: dark;
      --ink:#f4f0e7; --muted:#a5acb3; --line:rgba(255,255,255,.14);
      --panel:rgba(8,10,13,.82); --amber:#ffb45e; --cyan:#65d8ff;
      --ease:cubic-bezier(.22,1,.36,1);
    }
    * { box-sizing:border-box; }
    html,body { margin:0; width:100%; height:100%; overflow:hidden; background:#050608; color:var(--ink); }
    body { font-family:Avenir Next,Avenir,Inter,Helvetica Neue,system-ui,sans-serif; font-size:14px; }
    button,input { font:inherit; }
    button { color:inherit; }
    .app { position:relative; width:100%; height:100%; overflow:hidden; isolation:isolate; }
    .app::after { content:""; position:absolute; inset:0; pointer-events:none; z-index:5;
      background:radial-gradient(ellipse at center,transparent 50%,rgba(0,0,0,.32) 100%); }
    .topbar { position:absolute; top:0; left:0; right:0; z-index:30; height:76px; padding:0 28px;
      display:flex; align-items:center; gap:24px; background:linear-gradient(#050608 0%,rgba(5,6,8,.82) 60%,transparent);
      pointer-events:none; }
    .brand { display:flex; align-items:center; gap:12px; min-width:260px; pointer-events:auto; }
    .brand-mark { width:24px; height:24px; position:relative; }
    .brand-mark::before,.brand-mark::after { content:""; position:absolute; border:1px solid var(--amber); border-radius:50%; }
    .brand-mark::before { inset:1px 7px; transform:rotate(25deg); }
    .brand-mark::after { inset:7px 1px; transform:rotate(-25deg); }
    .brand-dot { position:absolute; width:4px; height:4px; border-radius:50%; background:#fff; left:10px; top:10px; box-shadow:0 0 10px white; }
    .brand-name { font-size:15px; letter-spacing:.22em; font-weight:600; }
    .brand-sub { color:var(--muted); font:10px "DM Mono",monospace; letter-spacing:.12em; text-transform:uppercase; margin-top:2px; }
    .search-wrap { width:min(420px,36vw); position:relative; margin:auto; pointer-events:auto; }
    .search { width:100%; border:1px solid var(--line); border-radius:2px; padding:11px 42px 11px 15px;
      background:rgba(8,10,13,.72); backdrop-filter:blur(14px); color:var(--ink); outline:none; transition:.2s; }
    .search:focus { border-color:rgba(255,180,94,.6); background:rgba(8,10,13,.9); }
    .search::placeholder { color:#747980; }
    .search-key { position:absolute; right:10px; top:9px; padding:2px 6px; border:1px solid var(--line);
      color:#71767d; font:10px "DM Mono"; }
    .count { min-width:260px; text-align:right; color:var(--muted); font:11px "DM Mono"; letter-spacing:.08em; pointer-events:auto; }
    .count b { color:var(--ink); font-weight:500; }
    .viewport { position:absolute; inset:0; z-index:1; overflow:hidden; cursor:grab; touch-action:none; background:#030405; }
    .viewport.dragging { cursor:grabbing; }
    .world { position:absolute; width:1600px; height:800px; transform-origin:0 0; will-change:transform; contain:layout paint style; }
    .sky { position:absolute; inset:0; width:100%; height:100%; object-fit:fill; user-select:none; pointer-events:none;
      filter:saturate(.86) contrast(1.06) brightness(.82); }
    .grid { position:absolute; inset:0; pointer-events:none; opacity:.26; mix-blend-mode:screen; }
    .grid path,.grid ellipse { fill:none; stroke:rgba(190,209,220,.24); stroke-width:.8; vector-effect:non-scaling-stroke; }
    .grid .major { stroke:rgba(255,255,255,.33); }
    .markers { position:absolute; inset:0; contain:layout paint style; }
    .marker { position:absolute; width:28px; height:28px; border:0; padding:0; background:none; cursor:pointer; z-index:2;
      transform:translate(-50%,-50%) scale(var(--marker-scale,1)); transform-origin:center; contain:layout paint style; }
    .marker-core { position:absolute; inset:0; width:28px; height:28px; transition:opacity .18s,filter .18s; }
    .marker-core::before { content:""; position:absolute; inset:9px; border-radius:50%; background:var(--dot,#ffb45e);
      box-shadow:0 0 8px var(--dot,#ffb45e),0 0 18px color-mix(in srgb,var(--dot,#ffb45e) 55%,transparent); }
    .marker-core::after { content:""; position:absolute; inset:3px; border:1px solid color-mix(in srgb,var(--dot,#ffb45e) 52%,transparent);
      border-radius:50%; opacity:.55; transform:scale(.65); transition:.25s var(--ease); }
    .marker:hover,.marker:focus-visible { z-index:8; outline:none; }
    .marker:hover .marker-core::after,.marker:focus-visible .marker-core::after { opacity:1; transform:scale(1); }
    .marker.is-muted { opacity:.1; pointer-events:none; }
    .marker.is-active .marker-core { filter:brightness(1.5); }
    .marker.is-active .marker-core::after { transform:scale(1.25); border-color:white; opacity:1; }
    .side-rail { position:absolute; z-index:20; left:26px; top:50%; transform:translateY(-50%); display:grid; gap:8px; }
    .tool { width:38px; height:38px; border:1px solid var(--line); background:rgba(8,10,13,.72); backdrop-filter:blur(12px);
      border-radius:2px; cursor:pointer; display:grid; place-items:center; font:18px "DM Mono"; transition:.2s; }
    .tool:hover { border-color:rgba(255,180,94,.55); background:#111317; }
    .tool-label { writing-mode:vertical-rl; transform:rotate(180deg); margin:10px auto 0; color:#747980;
      font:9px "DM Mono"; letter-spacing:.15em; text-transform:uppercase; }
    .filterbar { position:absolute; left:50%; bottom:24px; z-index:25; transform:translateX(-50%); display:flex; align-items:center; gap:3px;
      border:1px solid var(--line); padding:4px; border-radius:3px; background:rgba(8,10,13,.78); backdrop-filter:blur(18px); }
    .filter { border:0; background:transparent; padding:8px 12px; color:#80868d; cursor:pointer; border-radius:2px; font-size:11px; }
    .filter:hover { color:var(--ink); }
    .filter.active { color:#12100d; background:var(--amber); }
    .filter:focus-visible,.tool:focus-visible,.action:focus-visible,.close:focus-visible,.curve-mode:focus-visible {
      outline:2px solid var(--cyan); outline-offset:2px;
    }
    .scale-readout { position:absolute; z-index:20; right:26px; bottom:28px; color:#8c9299; font:10px "DM Mono"; text-align:right; }
    .scale-readout b { color:var(--ink); font-weight:400; }
    .legend { position:absolute; right:26px; top:96px; z-index:20; color:#92979d; font:10px "DM Mono"; line-height:1.8; text-align:right; }
    .legend i { display:inline-block; width:6px; height:6px; border-radius:50%; margin-left:8px; box-shadow:0 0 6px currentColor; }
    .tooltip { position:fixed; z-index:60; width:270px; pointer-events:none; opacity:0; transform:translateY(8px);
      transition:opacity .12s,transform .2s var(--ease); border:1px solid rgba(255,255,255,.16); background:rgba(7,9,12,.94);
      backdrop-filter:blur(18px); box-shadow:0 18px 50px rgba(0,0,0,.45); padding:15px; }
    .tooltip.show { opacity:1; transform:translateY(0); }
    .tip-head { display:flex; justify-content:space-between; gap:10px; align-items:flex-start; }
    .eyebrow { color:var(--amber); font:9px "DM Mono"; text-transform:uppercase; letter-spacing:.15em; }
    .tip-title { margin-top:4px; font-size:17px; font-weight:500; }
    .tip-amp { color:var(--cyan); font:14px "DM Mono"; }
    .tip-grid { display:grid; grid-template-columns:1fr 1fr; gap:10px; border-top:1px solid var(--line); margin-top:12px; padding-top:12px; }
    .tip-grid span { color:#737980; display:block; font:9px "DM Mono"; text-transform:uppercase; margin-bottom:3px; }
    .tip-grid b { font-weight:400; font-size:12px; }
    .tip-foot { color:#71767c; font:9px "DM Mono"; margin-top:12px; letter-spacing:.04em; }
    .loading { position:absolute; inset:0; z-index:100; background:#050608; display:grid; place-items:center; transition:opacity .55s; }
    .loading.hidden { opacity:0; pointer-events:none; }
    .load-inner { width:min(360px,80vw); text-align:center; }
    .load-orbit { width:46px; height:46px; margin:0 auto 22px; border:1px solid rgba(255,180,94,.3); border-top-color:var(--amber);
      border-radius:50%; animation:spin 1.2s linear infinite; }
    @keyframes spin { to { transform:rotate(360deg); } }
    .load-title { font:11px "DM Mono"; text-transform:uppercase; letter-spacing:.18em; }
    .load-message { color:var(--muted); font-size:12px; line-height:1.5; margin-top:12px; }
    .retry { display:none; margin:18px auto 0; border:1px solid var(--line); background:#11151a; padding:9px 16px; cursor:pointer; }
    .loading.error .load-orbit { display:none; }
    .loading.error .retry { display:block; }
    .load-line { height:1px; margin-top:18px; background:linear-gradient(90deg,transparent,var(--amber),transparent); animation:pulse 1.4s ease-in-out infinite; }
    @keyframes pulse { 50% { opacity:.25; } }
    .dialog { position:fixed; z-index:80; inset:0; border:0; margin:0; width:100%; height:100%; max-width:none; max-height:none;
      padding:0; background:rgba(3,4,6,.72); color:var(--ink); backdrop-filter:blur(16px); opacity:0; transition:opacity .22s; }
    .dialog[open] { opacity:1; }
    .dialog::backdrop { background:transparent; }
    .sheet { position:absolute; inset:18px; background:#090b0e; border:1px solid rgba(255,255,255,.14); overflow:hidden;
      display:grid; grid-template-columns:minmax(0,1.5fr) minmax(360px,.85fr); box-shadow:0 30px 100px rgba(0,0,0,.65); }
    .visual { position:relative; min-height:0; background:radial-gradient(circle at 62% 38%,#111a23 0,#080b10 42%,#050608 100%); overflow:hidden; }
    .visual::before { content:""; position:absolute; inset:0; opacity:.22; pointer-events:none;
      background-image:radial-gradient(circle,#fff 0 1px,transparent 1.5px); background-size:83px 83px; }
    .visual-head { position:absolute; z-index:3; left:26px; right:26px; top:22px; display:flex; justify-content:space-between; gap:18px; }
    .visual-head > div:first-child { min-width:0; }
    .view-title { font:10px "DM Mono"; letter-spacing:.12em; color:#a7adb4; text-transform:uppercase; }
    .schematic-note { max-width:520px; margin-top:6px; color:#c1c7cd; font:8px/1.45 "DM Mono"; letter-spacing:.05em; text-transform:uppercase; }
    .model-tag { color:var(--amber); font:9px "DM Mono"; border:1px solid rgba(255,180,94,.3); padding:5px 8px; }
    #lensing-svg { position:absolute; inset:0; width:100%; height:100%; shape-rendering:geometricPrecision; }
    .timeline { position:absolute; z-index:4; left:26px; right:26px; bottom:24px; background:rgba(5,7,9,.76);
      border:1px solid var(--line); padding:13px 15px; backdrop-filter:blur(12px); }
    .timeline-top { display:flex; justify-content:space-between; align-items:center; font:10px "DM Mono"; color:#92989e; margin-bottom:9px; }
    .timeline-top output { color:var(--cyan); }
    .range { width:100%; height:3px; appearance:none; background:linear-gradient(90deg,#394047,var(--amber),#394047); outline:none; cursor:pointer; }
    .range::-webkit-slider-thumb { appearance:none; width:13px; height:13px; border-radius:50%; background:#fff; box-shadow:0 0 0 4px rgba(255,180,94,.22); }
    .panel { min-height:0; overflow:auto; padding:28px 30px 36px; border-left:1px solid var(--line); scrollbar-color:#343940 transparent; }
    .close { position:absolute; z-index:7; top:31px; right:31px; width:34px; height:34px; border:1px solid var(--line);
      background:#0c0e12; cursor:pointer; font-size:18px; }
    .close:hover { border-color:var(--amber); }
    .detail-index { color:var(--amber); font:10px "DM Mono"; letter-spacing:.16em; text-transform:uppercase; }
    .detail-title { font-size:30px; line-height:1.1; font-weight:500; margin:8px 44px 4px 0; letter-spacing:-.02em; }
    .detail-sub { color:#777e85; font:10px "DM Mono"; word-break:break-all; }
    .hero-stats { display:grid; grid-template-columns:repeat(3,1fr); margin:24px 0 22px; border:1px solid var(--line); }
    .hero-stat { padding:14px; border-right:1px solid var(--line); }
    .hero-stat:last-child { border:0; }
    .hero-stat span { color:#777d84; display:block; font:8px "DM Mono"; text-transform:uppercase; letter-spacing:.09em; margin-bottom:6px; }
    .hero-stat b { font:17px "DM Mono"; font-weight:400; }
    .section { border-top:1px solid var(--line); padding-top:18px; margin-top:20px; }
    .section-title { font:9px "DM Mono"; color:#858b92; letter-spacing:.14em; text-transform:uppercase; margin-bottom:13px; }
    .data-row { display:grid; grid-template-columns:1fr auto; gap:18px; padding:7px 0; font-size:12px; }
    .data-row span:first-child { color:#848a91; }
    .data-row span:last-child { text-align:right; }
    .unknown { color:#8c9298!important; font-style:italic; }
    .source-card { padding:15px; border:1px solid var(--line); background:#0c0f13; }
    .source-name { font-size:14px; margin-bottom:5px; }
    .source-note { color:#7f868d; font-size:11px; line-height:1.55; }
    .source-note + .source-note { margin-top:8px; }
    .warning-note { margin-top:10px; color:#d8b67f; font-size:10px; line-height:1.55; }
    .category-strip { display:flex; flex-wrap:wrap; gap:8px; margin-top:14px; }
    .category-chip { border:1px solid rgba(255,255,255,.12); padding:7px 10px; font:10px "DM Mono"; color:#788089; background:#0a0d11; }
    .category-chip.active { border-color:rgba(255,180,94,.52); color:#f3efe6; background:rgba(255,180,94,.12); }
    .science-note { border-left:2px solid var(--amber); padding:2px 0 2px 12px; color:#8e959c; font-size:10px; line-height:1.6; }
    .curve { width:100%; height:132px; border:1px solid var(--line); background:#07090b; display:block; }
    .curve-controls { display:flex; flex-wrap:wrap; gap:5px; margin-bottom:9px; }
    .curve-mode { border:1px solid var(--line); background:#0b0e12; color:#aab1b8; padding:6px 8px; cursor:pointer; font:9px "DM Mono"; }
    .curve-mode.active { color:#15120e; border-color:var(--amber); background:var(--amber); }
    .curve-caption { margin-top:7px; color:#929aa2; font-size:10px; line-height:1.45; }
    .model-controls { border-top:1px solid var(--line); margin-top:14px; padding-top:12px; display:grid; gap:11px; }
    .model-control { display:grid; grid-template-columns:1fr auto; gap:6px 12px; color:#a5adb5; font:9px "DM Mono"; text-transform:uppercase; letter-spacing:.05em; }
    .model-control output { color:var(--cyan); }
    .model-control input { grid-column:1 / -1; width:100%; accent-color:var(--amber); }
    .model-result { display:grid; grid-template-columns:1fr auto; gap:12px; color:#a5adb5; font-size:11px; }
    .model-result b { color:var(--ink); font-weight:400; text-align:right; }
    .actions { display:flex; flex-wrap:wrap; gap:8px; margin-top:20px; }
    .action { flex:1 1 120px; border:1px solid var(--line); background:#101318; padding:10px; cursor:pointer; font-size:11px; }
    .action:hover { border-color:var(--amber); }
    .toast { position:fixed; z-index:120; left:50%; bottom:30px; transform:translate(-50%,18px); opacity:0; pointer-events:none;
      padding:10px 14px; background:#f3eee4; color:#111; font-size:11px; transition:.2s var(--ease); }
    .toast.show { opacity:1; transform:translate(-50%,0); }
    @media (max-width:900px) {
      .topbar { height:124px; padding:16px; align-items:flex-start; flex-wrap:wrap; }
      .brand { min-width:0; flex:1; }
      .brand-sub,.count { display:none; }
      .search-wrap { order:3; width:100%; flex-basis:100%; }
      .legend { display:none; }
      .side-rail { left:14px; }
      .filterbar { bottom:14px; max-width:calc(100vw - 28px); overflow:auto; }
      .scale-readout { display:none; }
      .sheet { inset:0; display:block; overflow:auto; }
      .visual { height:56vh; min-height:390px; }
      .panel { overflow:visible; border-left:0; border-top:1px solid var(--line); padding:26px 20px 40px; }
      .close { position:fixed; top:12px; right:12px; }
    }
    @media (max-width:600px) {
      .visual-head { left:16px; right:54px; top:16px; }
      .schematic-note { max-width:290px; line-height:1.45; letter-spacing:.04em; }
      .model-tag { display:none; }
      .timeline { left:14px; right:14px; bottom:14px; }
    }
    @media (prefers-reduced-motion:reduce) { *,*::before,*::after { animation-duration:.01ms!important; transition-duration:.01ms!important; } }
  </style>
</head>
<body>
<main class="app">
  <header class="topbar">
    <div class="brand">
      <div class="brand-mark"><i class="brand-dot"></i></div>
      <div><div class="brand-name">AURORA</div><div class="brand-sub">Atlas mikrosoczewkowania · Gaia DR3</div></div>
    </div>
    <div class="search-wrap">
      <input id="search" class="search" type="search" placeholder="Szukaj po ID Gaia lub AUR–ML…" autocomplete="off">
      <span class="search-key">/</span>
    </div>
    <div class="count"><b id="visible-count">—</b> / <span id="total-count">—</span> ZDARZEŃ</div>
  </header>

  <section id="viewport" class="viewport" aria-label="Interaktywna mapa nieba">
    <div id="world" class="world">
      <img id="sky" class="sky" src="/sky-map" alt="Mapa całego nieba AURORA w projekcji Hammera" draggable="false">
      <svg class="grid" viewBox="0 0 1600 800" preserveAspectRatio="none" aria-hidden="true">
        <ellipse class="major" cx="800" cy="400" rx="798" ry="398"/>
        <path d="M800 1V799M401 54Q800 400 401 746M1199 54Q800 400 1199 746M119 200Q800 400 119 600M1481 200Q800 400 1481 600"/>
        <path d="M30 300Q800 440 1570 300M30 500Q800 360 1570 500"/>
      </svg>
      <div id="markers" class="markers"></div>
    </div>
  </section>

  <aside class="side-rail" aria-label="Sterowanie mapą">
    <button class="tool" id="zoom-in" title="Przybliż">+</button>
    <button class="tool" id="zoom-out" title="Oddal">−</button>
    <button class="tool" id="reset" title="Pokaż całe niebo">⌾</button>
    <div class="tool-label">nawigacja</div>
  </aside>

  <div class="legend" aria-label="Legenda markerów amplifikacji">
    A<sub>max</sub> ≥ 2,0 <i style="color:#65d8ff;background:#65d8ff"></i><br>
    A<sub>max</sub> &lt; 2,0 <i style="color:#ffb45e;background:#ffb45e"></i>
  </div>
  <div class="filterbar" role="group" aria-label="Filtry zdarzeń">
    <button class="filter active" data-filter="all" aria-pressed="true">Wszystkie</button>
    <button class="filter" data-filter="strong" aria-pressed="false">Silne A≥2</button>
    <button class="filter" data-filter="short" aria-pressed="false">Krótkie ≤30 dni</button>
    <button class="filter" data-filter="long" aria-pressed="false">Długie ≥100 dni</button>
    <button class="filter" data-filter="catalog-mass" aria-pressed="false">Masa katalogowa</button>
    <button class="filter" data-filter="model-mass" aria-pressed="false">Hipoteza masy</button>
  </div>
  <div class="scale-readout">POWIĘKSZENIE<br><b id="zoom-readout">1.00×</b></div>
  <div id="tooltip" class="tooltip" role="tooltip"></div>
  <div id="loading" class="loading"><div class="load-inner"><div class="load-orbit"></div><div class="load-title">Ładowanie atlasu zdarzeń</div><div class="load-message" id="load-message"></div><div class="load-line"></div><button id="retry-load" class="retry">Spróbuj ponownie</button></div></div>
</main>

<dialog id="detail" class="dialog">
  <article class="sheet">
    <button id="close-detail" class="close" aria-label="Zamknij">×</button>
    <section class="visual">
      <div class="visual-head"><div><div class="view-title">Geometria zdarzenia · układ soczewki</div><div class="schematic-note">Schemat wykorzystuje przybliżenie cienkiej soczewki; odległości na ilustracji nie są przedstawione w skali.</div></div><div class="model-tag">PSPL / PACZYŃSKI</div></div>
      <svg id="lensing-svg" role="img" aria-label="Schemat geometrii mikrosoczewkowania"></svg>
      <div class="timeline">
        <div class="timeline-top"><span>CZAS WZGLĘDEM MAKSIMUM</span><output id="time-output">t = 0,00 tE</output></div>
        <input id="time-slider" class="range" type="range" min="-3" max="3" step=".01" value="0" aria-label="Czas względem maksimum">
      </div>
    </section>
    <section id="detail-panel" class="panel"></section>
  </article>
</dialog>
<div id="toast" class="toast">Skopiowano</div>

<script>
"use strict";
const $ = (selector, root=document) => root.querySelector(selector);
const $$ = (selector, root=document) => [...root.querySelectorAll(selector)];
const WORLD_W = 1600, WORLD_H = 800;
const state = {
  events: [], meta: null, scale: 1, tx: 0, ty: 0,
  targetScale: 1, targetTx: 0, targetTy: 0, minScale: 1, maxScale: 18,
  filter: "all", query: "", selected: null, dragging: false, moved: false,
  pointers: new Map(), lastPinch: null, raf: 0, markerNodes: [], markerByKey: new Map(),
  lastFocusedMarker: null, curveMode: "log"
};
const viewport = $("#viewport"), world = $("#world"), markers = $("#markers"), tooltip = $("#tooltip");
const fmt = (value, digits=1) => value == null ? "brak danych" : new Intl.NumberFormat("pl-PL",{maximumFractionDigits:digits}).format(value);
const pc = value => value == null ? "brak danych" : value >= 1000 ? `${fmt(value/1000,2)} kpc` : `${fmt(value,0)} pc`;
const superscriptInteger = value => String(value).replace("-", "⁻").replace(/[0-9]/g,digit=>"⁰¹²³⁴⁵⁶⁷⁸⁹"[Number(digit)]);
const formatSeparation = value => {
  if (value == null) return "brak danych";
  const magnitude=Math.abs(value);
  if (magnitude===0) return "0";
  if (magnitude<.001) {
    const exponent=Math.floor(Math.log10(magnitude));
    return `${(value/10**exponent).toFixed(2).replace(".",",")} × 10${superscriptInteger(exponent)}`;
  }
  return fmt(value,3);
};
const escapeHtml = value => String(value ?? "").replace(/[&<>"']/g,character=>({
  "&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"
})[character]);
const formatLensMass = value => {
  if (value == null) return "masa nieustalona";
  const digits=value<.01?5:value<.1?3:value<10?2:1;
  return `${fmt(value,digits)} M☉`;
};
const formatAmplification = value => {
  if (value < 10000) return `${fmt(value,2)}×`;
  const exponent=Math.floor(Math.log10(value));
  return `${(value/10**exponent).toFixed(2).replace(".",",")} × 10${superscriptInteger(exponent)}`;
};
const markerColour = event => event.aMax >= 2 ? "#65d8ff" : "#ffb45e";
const normalizeId = value => decodeURIComponent(value).replace(/[–—]/g,"-").toUpperCase();
const lensTheme = event => {
  if(event.massStatus==="catalog"){
    return {halo:"rgba(101,216,255,.22)",rim:"#88deff",body:"#050608",accent:"#d7f5ff",text:"SOCZEWKA · MASA KATALOGOWA"};
  }
  return {halo:"rgba(255,180,94,.2)",rim:"#ffb45e",body:"#050608",accent:"#f2eee4",text:event.massStatus==="model"?"SOCZEWKA · MODEL":"SOCZEWKA"};
};
const normalizedLensCategories = event => {
  const labels = [
    ["black-hole", "Czarne dziury"],
    ["neutron-star", "Gwiazdy neutronowe"],
    ["free-floating-planet", "Planety swobodne"],
  ];
  const categoryMap = new Map((event.lensCategories || []).map(item => [item.key, item]));
  return labels.map(([key, label]) => ({
    key,
    label,
    active: key === event.lensCategory,
    range: categoryMap.get(key) || null,
  }));
};
const massRegime = mass => {
  if (mass>=1e-6 && mass<=.013) return {key:"free-floating-planet",label:"zakres planety swobodnej"};
  if (mass>=1 && mass<=2.5) return {key:"neutron-star",label:"zakres gwiazdy neutronowej"};
  if (mass>=2.5 && mass<=120) return {key:"black-hole",label:"zakres czarnej dziury"};
  return {key:null,label:"poza trzema zakresami referencyjnymi"};
};
const modelMassFor = (event,speed,fraction) => {
  if (event.modelLensMass==null || !(fraction>0&&fraction<1)) return null;
  return event.modelLensMass*(speed/100)**2*.25/(fraction*(1-fraction));
};

function fitMap(immediate=false) {
  const rect = viewport.getBoundingClientRect();
  state.minScale = Math.min(rect.width / WORLD_W, rect.height / WORLD_H) * .92;
  state.maxScale = state.minScale * 20;
  state.targetScale = state.minScale;
  state.targetTx = (rect.width - WORLD_W * state.minScale) / 2;
  state.targetTy = (rect.height - WORLD_H * state.minScale) / 2;
  applyTarget(immediate);
}

function clampTarget() {
  const rect=viewport.getBoundingClientRect(), w=WORLD_W*state.targetScale, h=WORLD_H*state.targetScale;
  const margin=80;
  state.targetTx = w <= rect.width ? (rect.width-w)/2 : Math.min(margin,Math.max(rect.width-w-margin,state.targetTx));
  state.targetTy = h <= rect.height ? (rect.height-h)/2 : Math.min(margin,Math.max(rect.height-h-margin,state.targetTy));
}
function syncToTarget() {
  if (state.raf) {
    cancelAnimationFrame(state.raf);
    state.raf = 0;
  }
  state.scale=state.targetScale; state.tx=state.targetTx; state.ty=state.targetTy; renderTransform();
}
function renderTransform() {
  world.style.transform=`translate3d(${state.tx}px,${state.ty}px,0) scale(${state.scale})`;
  world.style.setProperty("--marker-scale",Math.min(1.4,Math.max(.55,1/state.scale)));
  $("#zoom-readout").textContent=`${(state.scale/state.minScale).toFixed(2)}×`;
}
function applyTarget(immediate=false) {
  if (immediate) syncToTarget();
  else animate();
}
function animate() {
  if (state.raf) return;
  const tick=()=>{
    state.scale += (state.targetScale-state.scale)*.16;
    state.tx += (state.targetTx-state.tx)*.16;
    state.ty += (state.targetTy-state.ty)*.16;
    renderTransform();
    if (Math.abs(state.scale-state.targetScale)>.0002 || Math.abs(state.tx-state.targetTx)>.05 || Math.abs(state.ty-state.targetTy)>.05) {
      state.raf=requestAnimationFrame(tick);
    } else {
      state.scale=state.targetScale; state.tx=state.targetTx; state.ty=state.targetTy; state.raf=0; renderTransform();
    }
  };
  state.raf=requestAnimationFrame(tick);
}
function zoomAt(factor,cx,cy,immediate=false) {
  const old=state.targetScale, next=Math.min(state.maxScale,Math.max(state.minScale,old*factor));
  const wx=(cx-state.targetTx)/old, wy=(cy-state.targetTy)/old;
  state.targetScale=next; state.targetTx=cx-wx*next; state.targetTy=cy-wy*next;
  clampTarget();
  applyTarget(immediate);
}
function centerEvent(event) {
  const rect=viewport.getBoundingClientRect(), next=Math.max(state.minScale*4,Math.min(state.maxScale,state.targetScale));
  state.targetScale=next; state.targetTx=rect.width/2-event.x*WORLD_W*next; state.targetTy=rect.height/2-event.y*WORLD_H*next;
  clampTarget(); applyTarget();
}

viewport.addEventListener("wheel",event=>{
  event.preventDefault();
  const rect=viewport.getBoundingClientRect();
  zoomAt(Math.exp(-event.deltaY*.0015),event.clientX-rect.left,event.clientY-rect.top);
},{passive:false});
viewport.addEventListener("pointerdown",event=>{
  if (event.target.closest(".marker")) return;
  viewport.setPointerCapture(event.pointerId); state.pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});
  state.dragging=true; state.moved=false; viewport.classList.add("dragging");
});
viewport.addEventListener("pointermove",event=>{
  if (!state.pointers.has(event.pointerId)) return;
  const prev=state.pointers.get(event.pointerId), current={x:event.clientX,y:event.clientY};
  state.pointers.set(event.pointerId,current);
  if (state.pointers.size===1) {
    state.targetTx += current.x-prev.x; state.targetTy += current.y-prev.y;
    if(Math.abs(current.x-prev.x)+Math.abs(current.y-prev.y)>1) state.moved=true;
    clampTarget(); syncToTarget(); return;
  } else if (state.pointers.size===2) {
    const points=[...state.pointers.values()], distance=Math.hypot(points[0].x-points[1].x,points[0].y-points[1].y);
    const center={x:(points[0].x+points[1].x)/2,y:(points[0].y+points[1].y)/2};
    if(state.lastPinch) zoomAt(distance/state.lastPinch.distance,center.x,center.y,true);
    state.lastPinch={distance,center};
    return;
  }
});
function endPointer(event) {
  state.pointers.delete(event.pointerId); state.lastPinch=null;
  if(!state.pointers.size){state.dragging=false;viewport.classList.remove("dragging");}
}
viewport.addEventListener("pointerup",endPointer); viewport.addEventListener("pointercancel",endPointer);
viewport.addEventListener("dblclick",event=>{
  const rect=viewport.getBoundingClientRect(); zoomAt(1.8,event.clientX-rect.left,event.clientY-rect.top);
});
$("#zoom-in").addEventListener("click",()=>zoomAt(1.55,viewport.clientWidth/2,viewport.clientHeight/2));
$("#zoom-out").addEventListener("click",()=>zoomAt(1/1.55,viewport.clientWidth/2,viewport.clientHeight/2));
$("#reset").addEventListener("click",()=>fitMap());

function createMarkers() {
  const fragment=document.createDocumentFragment();
  state.markerNodes = [];
  state.markerByKey = new Map();
  state.events.forEach(event=>{
    const button=document.createElement("button"); button.className="marker"; button.dataset.key=event.key;
    button.dataset.index=String(state.markerNodes.length);
    button.style.left=`${event.x*100}%`; button.style.top=`${event.y*100}%`;
    button.setAttribute("aria-label",`${event.name}, maksimum ${event.date.label}`);
    button.innerHTML=`<span class="marker-core" style="--dot:${markerColour(event)}"></span>`;
    state.markerNodes.push(button);
    state.markerByKey.set(event.key,button);
    fragment.appendChild(button);
  });
  markers.replaceChildren(fragment); updateFilter();
}
function markerEvent(target) {
  const marker=target.closest(".marker");
  if (!marker) return null;
  return state.events[Number(marker.dataset.index)] || null;
}
markers.addEventListener("pointerover",pointerEvent=>{
  const event=markerEvent(pointerEvent.target);
  if (!event) return;
  showTooltip(event,pointerEvent);
});
markers.addEventListener("pointermove",pointerEvent=>{
  if (pointerEvent.target.closest(".marker")) moveTooltip(pointerEvent);
});
markers.addEventListener("pointerout",pointerEvent=>{
  if (!pointerEvent.relatedTarget || !pointerEvent.relatedTarget.closest(".marker")) hideTooltip();
});
markers.addEventListener("focusin",focusEvent=>{
  const event=markerEvent(focusEvent.target);
  if (event) showTooltip(event,{clientX:innerWidth/2,clientY:innerHeight/2});
});
markers.addEventListener("focusout",hideTooltip);
markers.addEventListener("click",clickEvent=>{
  const event=markerEvent(clickEvent.target);
  if (!event) return;
  hideTooltip();
  openDetail(event);
});
markers.addEventListener("dblclick",dblClickEvent=>{
  const event=markerEvent(dblClickEvent.target);
  if (!event) return;
  dblClickEvent.stopPropagation();
  centerEvent(event);
});
function showTooltip(event,pointerEvent) {
  tooltip.innerHTML=`<div class="tip-head"><div><div class="eyebrow">Zdarzenie ${event.catalogIndex}/${state.meta.count}</div><div class="tip-title">${escapeHtml(event.name)}</div></div><div class="tip-amp">A ${fmt(event.aMax,2)}×</div></div>
  <div class="tip-grid"><div><span>Maksimum</span><b>${escapeHtml(event.date.label)}</b></div><div><span>Czas tE</span><b>${fmt(event.te,1)} dni</b></div><div><span>Jasność źródła</span><b>${event.gMag==null?"—":fmt(event.gMag,2)+" mag"}</b></div><div><span>Położenie</span><b>l ${fmt(event.l,1)}° · b ${fmt(event.b,1)}°</b></div></div><div class="tip-foot">KLIKNIJ, ABY OTWORZYĆ PEŁNĄ KARTĘ →</div>`;
  tooltip.classList.add("show"); moveTooltip(pointerEvent);
}
function moveTooltip(event) {
  const gap=18,w=270,h=190;
  let x=event.clientX+gap,y=event.clientY+gap;
  if(x+w>innerWidth-10)x=event.clientX-w-gap;
  if(y+h>innerHeight-10)y=event.clientY-h-gap;
  tooltip.style.left=`${Math.max(10,x)}px`;tooltip.style.top=`${Math.max(10,y)}px`;
}
function hideTooltip(){tooltip.classList.remove("show");}

function eventMatches(event,query) {
  const filterOk=state.filter==="all" || (state.filter==="strong"&&event.aMax>=2) ||
    (state.filter==="short"&&event.te<=30) || (state.filter==="long"&&event.te>=100) ||
    (state.filter==="catalog-mass"&&event.massStatus==="catalog") ||
    (state.filter==="model-mass"&&event.massStatus==="model");
  return filterOk && (!query || event.searchId.includes(query) || event.searchName.includes(query));
}
function updateFilter() {
  let visible=0;
  const query=state.query.replace(/[–—]/g,"-").toLowerCase();
  state.markerNodes.forEach((marker,index)=>{
    const match=eventMatches(state.events[index],query); marker.classList.toggle("is-muted",!match); if(match)visible++;
  });
  $("#visible-count").textContent=visible; $("#total-count").textContent=state.events.length;
}
$$(".filter").forEach(button=>button.addEventListener("click",()=>{
  $$(".filter").forEach(item=>{
    const active=item===button;
    item.classList.toggle("active",active);
    item.setAttribute("aria-pressed",String(active));
  });
  state.filter=button.dataset.filter;
  const url=new URL(location.href);
  if(state.filter==="all")url.searchParams.delete("filter");else url.searchParams.set("filter",state.filter);
  history.replaceState(null,"",url);
  updateFilter();
}));
$("#search").addEventListener("input",event=>{state.query=event.target.value.trim();updateFilter();});
markers.addEventListener("keydown",keyboardEvent=>{
  if(!["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(keyboardEvent.key))return;
  const visible=state.markerNodes.filter(marker=>!marker.classList.contains("is-muted"));
  const current=visible.indexOf(keyboardEvent.target.closest(".marker"));
  if(current<0||!visible.length)return;
  keyboardEvent.preventDefault();
  const direction=keyboardEvent.key==="ArrowLeft"||keyboardEvent.key==="ArrowUp"?-1:1;
  visible[(current+direction+visible.length)%visible.length].focus();
});

function openDetail(event) {
  state.selected=event; $("#time-slider").value=0;
  event.visualLensMass=event.lensMass;
  event.visualLensCategory=event.lensCategory;
  state.lastFocusedMarker=document.activeElement?.closest?.(".marker")||state.markerByKey.get(event.key)||null;
  state.markerNodes.forEach(marker=>marker.classList.toggle("is-active",marker.dataset.key===event.key));
  renderDetailPanel(event);
  const dialog=$("#detail"); if(!dialog.open)dialog.showModal();
  requestAnimationFrame(()=>{updateSimulation();$("#close-detail").focus();});
  const url=new URL(location.href);url.hash=event.name.replaceAll("–","-");history.replaceState(null,"",url);
}
function closeDetail() {
  const dialog=$("#detail"); if(dialog.open)dialog.close();
  state.selected=null; state.markerNodes.forEach(marker=>marker.classList.remove("is-active"));
  const url=new URL(location.href);url.hash="";history.replaceState(null,"",url);
  state.lastFocusedMarker?.focus();
}
$("#close-detail").addEventListener("click",closeDetail);
$("#detail").addEventListener("click",event=>{if(event.target===$("#detail"))closeDetail();});

function renderDetailPanel(event) {
  const lensMass=event.lensMass==null?"Nieustalona":`${event.massStatus==="model"?"≈ ":""}${formatLensMass(event.lensMass)}`;
  const lensKind=event.lensKind||(
    event.massStatus==="catalog"
      ? "Masa katalogowa bez identyfikacji typu obiektu"
      : "Brak bezpośredniej identyfikacji soczewki"
  );
  const massStatus=event.massStatus==="catalog"?"wartość katalogowa":event.massStatus==="model"?"hipoteza modelowa":"brak danych";
  const regime=event.lensHypothesis?`zgodność z zakresem: ${event.lensHypothesis}`:"brak zgodności z trzema zakresami";
  const temp=event.temperature==null?"brak danych":`${fmt(event.temperature,0)} K`;
  const categoryChips=normalizedLensCategories(event).map(category=>
    `<span class="category-chip ${category.active?"active":""}" data-category="${category.key}">${escapeHtml(category.label)}</span>`
  ).join("");
  const parallaxValue=event.parallax==null?"brak danych":`${fmt(event.parallax,4)} ± ${event.parallaxError==null?"?":fmt(event.parallaxError,4)} mas`;
  const relativeError=event.parallaxRelativeError==null?"brak danych":`${fmt(event.parallaxRelativeError*100,1)}%`;
  const distanceInterval=event.distanceLowPc==null
    ?"brak przedziału bez σϖ"
    : `${pc(event.distanceLowPc)} – ${event.distanceHighPc==null?"nieograniczona":pc(event.distanceHighPc)}`;
  const parallaxWarning=event.parallaxError==null
    ?"Katalog lokalny nie zawiera parallax_error. Uruchom ponownie moduł katalogowy, aby pobrać niepewności."
    : event.parallaxRelativeError>.2
      ?"Duży względny błąd paralaksy: prosta odwrotność 1/ϖ może być silnie obciążona."
      :"Odległość 1/ϖ jest tylko przybliżeniem i nie uwzględnia punktu zerowego Gaia ani prioru odległości.";
  const modelControls=event.massStatus==="model"?`
      <div class="model-controls">
        <label class="model-control">Prędkość poprzeczna v⊥ <output id="model-speed-output">100 km/s</output>
          <input id="model-speed" type="range" min="30" max="300" step="5" value="100">
        </label>
        <label class="model-control">Położenie soczewki Dₗ/Dₛ <output id="model-distance-output">0,50</output>
          <input id="model-distance" type="range" min=".10" max=".90" step=".01" value=".50">
        </label>
        <div class="model-result"><span>Masa dla scenariusza</span><b id="model-mass">${lensMass}</b></div>
        <div class="model-result"><span>Zgodność zakresu</span><b id="model-regime">${escapeHtml(regime)}</b></div>
      </div>`:"";
  $("#detail-panel").innerHTML=`
    <div class="detail-index">Karta zdarzenia ${event.catalogIndex} / ${state.meta.count}</div>
    <h1 class="detail-title">${escapeHtml(event.name)}</h1><div class="detail-sub">Gaia DR3 ${escapeHtml(event.sourceId)}</div>
    <div class="hero-stats">
      <div class="hero-stat"><span>Maks. amplifikacja</span><b>${fmt(event.aMax,2)}×</b></div>
      <div class="hero-stat"><span>Skala czasu tE</span><b>${fmt(event.te,1)} d</b></div>
      <div class="hero-stat"><span>Parametr u₀</span><b>${formatSeparation(event.u0)}</b></div>
    </div>
    <section class="section"><div class="section-title">Czas i położenie</div>
      <div class="data-row"><span>Data kalendarzowa UTC (prezentacja)</span><span>${escapeHtml(event.date.label)}</span></div>
      <div class="data-row"><span>Czas maksimum, BJD(TCB)</span><span>${fmt(event.date.bjd,5)}</span></div>
      <div class="data-row"><span>Długość galaktyczna l</span><span>${fmt(event.l,5)}°</span></div>
      <div class="data-row"><span>Szerokość galaktyczna b</span><span>${fmt(event.b,5)}°</span></div>
    </section>
    <section class="section"><div class="section-title">Obiekt soczewkujący</div>
      <div class="source-card"><div class="source-name ${event.lensKind||event.massStatus==="catalog"?"":"unknown"}">${escapeHtml(lensKind)}</div>
      <div class="source-note">${escapeHtml(event.lensInferenceNote)}</div>
      ${event.massEstimateNote?`<div class="source-note">${escapeHtml(event.massEstimateNote)}</div>`:""}
      <div class="category-strip" aria-label="Referencyjne zakresy masy">${categoryChips}</div>
      ${modelControls}</div>
      <div class="data-row"><span>Status masy</span><span>${escapeHtml(massStatus)}</span></div>
      <div class="data-row"><span>${event.massStatus==="catalog"?"Masa soczewki":"Domyślna masa scenariusza"}</span><span class="${event.lensMass==null?"unknown":""}">${lensMass}</span></div>
      ${event.massStatus==="model"?`<div class="data-row"><span>Zakres scenariuszy 50–200 km/s</span><span>${formatLensMass(event.modelMassLow)} – ${formatLensMass(event.modelMassHigh)}</span></div>`:""}
      <div class="data-row"><span>Identyfikacja obiektu</span><span class="${event.lensKind?"":"unknown"}">${event.lensKind?escapeHtml(event.lensKind):"brak wystarczających danych"}</span></div>
      ${event.lensKind?`<div class="data-row"><span>Opis katalogowy</span><span>${escapeHtml(event.lensKind)}</span></div>`:""}
      <div class="data-row"><span>Model dopasowania</span><span>Punktowe źródło + punktowa soczewka</span></div>
      <div class="data-row"><span>Kaustyka PSPL</span><span>Punkt; brak skończonej klasycznej kaustyki</span></div>
      <div class="data-row"><span>Krzywa krytyczna</span><span>Okrąg Einsteina w płaszczyźnie obrazu</span></div>
    </section>
    <section class="section"><div class="section-title">Gwiazda soczewkowana</div>
      <div class="source-card"><div class="source-name">${escapeHtml(event.sourceDescription)}</div>
      <div class="source-note">Jasność G: ${event.gMag==null?"brak danych":fmt(event.gMag,3)+" mag"} · temperatura: ${temp}${event.temperatureOrigin?" ("+escapeHtml(event.temperatureOrigin)+")":""}</div></div>
      <div class="data-row"><span>Paralaksa Gaia ϖ ± σϖ</span><span>${parallaxValue}</span></div>
      <div class="data-row"><span>Względny błąd σϖ/ϖ</span><span>${relativeError}</span></div>
      <div class="data-row"><span>Odległość 1/ϖ (orientacyjna)</span><span>${pc(event.distancePc)}</span></div>
      <div class="data-row"><span>Przedział z ϖ ± σϖ</span><span>${distanceInterval}</span></div>
      <div class="data-row"><span>Barwa BP−RP</span><span>${event.bpRp==null?"brak danych":fmt(event.bpRp,3)+" mag"}</span></div>
      <div class="warning-note">${escapeHtml(parallaxWarning)}</div>
    </section>
    <section class="section"><div class="section-title">Krzywa Paczyńskiego</div>
      <div class="curve-controls" role="group" aria-label="Tryb skali krzywej">
        <button class="curve-mode" data-curve-mode="linear" aria-pressed="false">A liniowo</button>
        <button class="curve-mode active" data-curve-mode="log" aria-pressed="true">log A</button>
        <button class="curve-mode" data-curve-mode="magnitude" aria-pressed="false">Δmag</button>
      </div>
      <svg id="curve-canvas" class="curve" role="img" aria-label="Modelowa krzywa Paczyńskiego"></svg>
      <div class="curve-caption">Wyłącznie model PSPL z parametrów katalogowych. Lokalny FITS nie zawiera fotometrii epochowej ani niepewności parametrów dopasowania.</div>
    </section>
    <section class="section"><div class="science-note">Wizualizacja jest znormalizowana do promienia Einsteina. Źródło i obserwator są nieruchome, a soczewka porusza się po prostej ze stałą prędkością; τ = 0 oznacza najmniejsze zbliżenie, nie punkt zawracania. Promienie biegną po dwóch prostych odcinkach i zmieniają kierunek wyłącznie w płaszczyźnie cienkiej soczewki. Panel obrazu zachowuje dokładne położenia punktowych obrazów θ+ i θ−, a dodatkowo mapuje poglądowy dysk źródła o ρvis = 0,05 θE. Ta warstwa pokazuje fizyczne przejście obrazów rozciągłych w łuki i niemal pełny pierścień, ale nie jest dopasowanym parametrem katalogowym i nie zmienia krzywej PSPL. Matematycznie cienki pierścień Einsteina nadal odpowiada dokładnemu u = 0.</div></section>
    <div class="actions"><button id="copy-id" class="action">Kopiuj ID Gaia</button><button id="copy-link" class="action">Kopiuj link</button><button id="export-json" class="action">Eksport JSON</button><button id="export-csv" class="action">Eksport CSV</button><button id="focus-map" class="action">Pokaż na mapie</button></div>`;
  $("#copy-id").addEventListener("click",()=>copyText(event.sourceId));
  $("#copy-link").addEventListener("click",()=>copyText(location.href));
  $("#export-json").addEventListener("click",()=>downloadEvent(event,"json"));
  $("#export-csv").addEventListener("click",()=>downloadEvent(event,"csv"));
  $("#focus-map").addEventListener("click",()=>{closeDetail();centerEvent(event);});
  $$(".curve-mode",$("#detail-panel")).forEach(button=>button.addEventListener("click",()=>{
    state.curveMode=button.dataset.curveMode;
    $$(".curve-mode",$("#detail-panel")).forEach(item=>{
      const active=item===button;item.classList.toggle("active",active);item.setAttribute("aria-pressed",String(active));
    });
    drawCurve(event,Number($("#time-slider").value));
  }));
  if(event.massStatus==="model"){
    const update=()=>updateModelHypothesis(event);
    $("#model-speed").addEventListener("input",update);
    $("#model-distance").addEventListener("input",update);
  }
  drawCurve(event,0);
}
function updateModelHypothesis(event) {
  const speed=Number($("#model-speed").value),fraction=Number($("#model-distance").value);
  const mass=modelMassFor(event,speed,fraction),regime=massRegime(mass);
  event.visualLensMass=mass;event.visualLensCategory=regime.key;
  $("#model-speed-output").textContent=`${fmt(speed,0)} km/s`;
  $("#model-distance-output").textContent=fmt(fraction,2);
  $("#model-mass").textContent=`≈ ${formatLensMass(mass)}`;
  $("#model-regime").textContent=regime.label;
  $$(".category-chip",$("#detail-panel")).forEach(chip=>chip.classList.toggle("active",chip.dataset.category===regime.key));
  updateSimulation();
}
function downloadEvent(event,format) {
  let content,type,extension;
  if(format==="csv"){
    const fields=["name","sourceId","l","b","tmax","te","u0","aMax","parallax","parallaxError","distancePc","lensMass","massStatus"];
    const quote=value=>`"${String(value??"").replaceAll('"','""')}"`;
    content=`${fields.join(",")}\n${fields.map(field=>quote(event[field])).join(",")}\n`;
    type="text/csv;charset=utf-8";extension="csv";
  }else{
    content=JSON.stringify(event,null,2);type="application/json;charset=utf-8";extension="json";
  }
  const url=URL.createObjectURL(new Blob([content],{type}));
  const link=document.createElement("a");link.href=url;link.download=`${event.name.replaceAll("–","-")}.${extension}`;link.click();
  setTimeout(()=>URL.revokeObjectURL(url),0);
}
async function copyText(text) {
  try { await navigator.clipboard.writeText(text); } catch { const area=document.createElement("textarea");area.value=text;document.body.appendChild(area);area.select();document.execCommand("copy");area.remove(); }
  const toast=$("#toast");toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),1300);
}

function amplification(tau,u0) {
  const u2=Math.max(1e-24,u0*u0+tau*tau); return (u2+2)/Math.sqrt(u2*(u2+4));
}
function pointLensState(u0,tau) {
  const impact=Number.isFinite(u0)?u0:0;
  const phase=Number.isFinite(tau)?tau:0;
  const u2=impact*impact+phase*phase;
  const u=Math.sqrt(u2),root=Math.sqrt(u2+4);
  const thetaPlus=.5*(u+root);
  const thetaMinusRaw=.5*(u-root);
  const thetaMinus=thetaMinusRaw===0&&u>0?-2/(u+root):thetaMinusRaw;
  const safeU=Math.max(u,1e-12);
  const total=(u2+2)/(safeU*root);
  const muPlus=.5*(1+total),muMinus=Math.max(0,.5*(total-1));
  const lensOffset={x:phase,y:impact},sourceOffset={x:-phase,y:-impact};
  const direction=u>0?{x:sourceOffset.x/u,y:sourceOffset.y/u}:{x:-1,y:0};
  return {
    u,u2,thetaPlus,thetaMinus,muPlus,muMinus,
    amplification:muPlus+muMinus,direction,lensOffset,sourceOffset,
    aligned:u2===0,
  };
}
const FINITE_SOURCE_DISPLAY_RADIUS=.05;
function finiteSourceImageContours(sourceOffset,radius=FINITE_SOURCE_DISPLAY_RADIUS,samples=80) {
  const plus=[],minus=[];
  for(let index=0;index<samples;index++){
    const angle=2*Math.PI*(index+.5)/samples;
    const betaX=sourceOffset.x+radius*Math.cos(angle);
    const betaY=sourceOffset.y+radius*Math.sin(angle);
    const beta=Math.hypot(betaX,betaY);
    const unit=beta>1e-10
      ? {x:betaX/beta,y:betaY/beta}
      : {x:Math.cos(angle+Math.PI/2),y:Math.sin(angle+Math.PI/2)};
    const root=Math.sqrt(beta*beta+4);
    const thetaPlus=.5*(beta+root);
    const thetaMinus=-2/(beta+root);
    plus.push({x:unit.x*thetaPlus,y:unit.y*thetaPlus});
    minus.push({x:unit.x*thetaMinus,y:unit.y*thetaMinus});
  }
  return {
    plus,minus,
    containsCaustic:Math.hypot(sourceOffset.x,sourceOffset.y)<radius,
  };
}
window.AURORA_PSPL=Object.freeze({
  solve:pointLensState,
  finiteSourceContours:finiteSourceImageContours,
  finiteSourceDisplayRadius:FINITE_SOURCE_DISPLAY_RADIUS,
});
function drawCurve(event,tau) {
  const canvas=$("#curve-canvas");if(!canvas)return;
  const w=Math.max(280,canvas.getBoundingClientRect().width),h=132;
  canvas.setAttribute("viewBox",`0 0 ${w} ${h}`);
  const pad={l:38,r:12,t:17,b:24},plotW=w-pad.l-pad.r,plotH=h-pad.t-pad.b;
  const peak=Math.max(1+1e-12,event.aMax);
  const transform=value=>{
    if(state.curveMode==="linear")return value-1;
    if(state.curveMode==="magnitude")return 2.5*Math.log10(value);
    return Math.log10(value);
  };
  const peakValue=Math.max(1e-12,transform(peak));
  const points=[];
  for(let i=0;i<=260;i++){
    const t=-3+6*i/260,a=amplification(t,event.u0);
    const x=pad.l+plotW*i/260,y=pad.t+plotH*(1-transform(a)/peakValue);
    points.push(`${x.toFixed(1)},${y.toFixed(1)}`);
  }
  const cx=pad.l+plotW*(tau+3)/6;
  const currentAmp=amplification(tau,event.u0);
  const currentLabel=state.curveMode==="magnitude"
    ? `ΔG = −${fmt(2.5*Math.log10(currentAmp),2)} mag`
    : `A ${formatAmplification(currentAmp)}`;
  const modeLabel=state.curveMode==="linear"?"A · SKALA LINIOWA":state.curveMode==="magnitude"?"ZMIANA JASNOŚCI ΔG":"log₁₀ A";
  const grid=Array.from({length:5},(_,i)=>{const y=pad.t+plotH*i/4;return `<line x1="${pad.l}" y1="${y}" x2="${w-pad.r}" y2="${y}" stroke="rgba(255,255,255,.09)"/>`;}).join("");
  canvas.innerHTML=`<title>Modelowa krzywa Paczyńskiego</title><desc>${modeLabel}; maksimum nie jest obcinane.</desc>
    ${grid}<polyline points="${points.join(" ")}" fill="none" stroke="#ffb45e" stroke-width="1.7"/>
    <line x1="${cx}" y1="${pad.t}" x2="${cx}" y2="${h-pad.b}" stroke="#65d8ff"/>
    <g fill="#a5acb3" font-size="9" font-family="DM Mono,monospace"><text x="${pad.l}" y="${h-7}">−3 tE</text><text x="${w-pad.r-30}" y="${h-7}">+3 tE</text><text x="${pad.l}" y="${pad.t+9}">${modeLabel}</text></g>
    <text x="${w-pad.r}" y="${pad.t+9}" text-anchor="end" fill="#65d8ff" font-size="9" font-family="DM Mono,monospace">${currentLabel}</text>`;
}
function updateSimulation() {
  const event=state.selected;if(!event)return;
  const tau=Number($("#time-slider").value),lensState=pointLensState(event.u0,tau);
  $("#time-output").textContent=`t = ${tau>=0?"+":""}${fmt(tau,2)} tE · A = ${formatAmplification(lensState.amplification)}`;
  drawLensing(event,lensState,tau);drawCurve(event,tau);
}
let simulationFrame=0;
function scheduleSimulation() {
  if(simulationFrame)return;
  simulationFrame=requestAnimationFrame(()=>{simulationFrame=0;updateSimulation();});
}
$("#time-slider").addEventListener("input",scheduleSimulation);

function drawLensing(event,lensState,tau) {
  const canvas=$("#lensing-svg"),rect=canvas.getBoundingClientRect(),w=Math.max(360,rect.width),h=Math.max(390,rect.height);
  canvas.setAttribute("viewBox",`0 0 ${w} ${h}`);
  const sourceColour=event.sourceColor?.css || "#d9f0ff";
  const {
    u,thetaPlus,thetaMinus,muPlus,muMinus,amplification:amp,
    direction,lensOffset,sourceOffset,aligned,
  }=lensState;
  const theme=lensTheme(event);
  const axisY=h*.63,observer={x:w*.11,y:axisY},source={x:w*.89,y:axisY};
  const lensOrigin={x:w*.5,y:axisY};
  const trackDir={x:.34,y:Math.sqrt(1-.34*.34)},impactDir={x:-Math.sqrt(1-.34*.34),y:.34};
  const trajectoryExtent=Math.max(1,Math.hypot(3.25,lensOffset.y));
  const trajectoryScale=Math.min(36,Math.min(w*.17,h*.16)/trajectoryExtent);
  const closest={
    x:lensOrigin.x+impactDir.x*lensOffset.y*trajectoryScale,
    y:lensOrigin.y+impactDir.y*lensOffset.y*trajectoryScale,
  };
  const lens={
    x:closest.x+trackDir.x*lensOffset.x*trajectoryScale,
    y:closest.y+trackDir.y*lensOffset.x*trajectoryScale,
  };
  const trackStart={x:closest.x-trackDir.x*3.25*trajectoryScale,y:closest.y-trackDir.y*3.25*trajectoryScale};
  const trackEnd={x:closest.x+trackDir.x*3.25*trajectoryScale,y:closest.y+trackDir.y*3.25*trajectoryScale};
  const projectedSource={
    x:trackDir.x*sourceOffset.x+impactDir.x*sourceOffset.y,
    y:trackDir.y*sourceOffset.x+impactDir.y*sourceOffset.y,
  };
  const imageAxis=u>0
    ? {x:projectedSource.x/u,y:projectedSource.y/u}
    : {x:-trackDir.x,y:-trackDir.y};
  const bendScale=trajectoryScale*.82;
  const bendPlus={x:lens.x+imageAxis.x*thetaPlus*bendScale,y:lens.y+imageAxis.y*thetaPlus*bendScale};
  const bendMinus={x:lens.x+imageAxis.x*thetaMinus*bendScale,y:lens.y+imageAxis.y*thetaMinus*bendScale};
  const planeHalf=Math.max(Math.abs(thetaPlus),Math.abs(thetaMinus))*bendScale+12;
  const planeStart={x:lens.x-imageAxis.x*planeHalf,y:lens.y-imageAxis.y*planeHalf};
  const planeEnd={x:lens.x+imageAxis.x*planeHalf,y:lens.y+imageAxis.y*planeHalf};
  const totalMu=Math.max(1e-12,muPlus+muMinus);
  const sharePlus=muPlus/totalMu,shareMinus=muMinus/totalMu;
  const rayPlusWidth=1.1+3.2*Math.sqrt(sharePlus),rayMinusWidth=1.1+3.2*Math.sqrt(shareMinus);
  const rayPlusOpacity=.28+.7*Math.sqrt(sharePlus),rayMinusOpacity=.28+.7*Math.sqrt(shareMinus);
  const panelWidth=Math.min(238,Math.max(148,(w-54)/2,w*.28));
  const panelHeight=Math.min(130,Math.max(108,h*.255));
  const panelTop=Math.max(66,h*.13);
  const imageInset={x:18,y:panelTop,width:panelWidth,height:panelHeight};
  const sourceInset={x:w-panelWidth-18,y:panelTop,width:panelWidth,height:panelHeight};
  const imageCentre={x:imageInset.x+imageInset.width*.5,y:imageInset.y+imageInset.height*.68};
  const imageExtent=Math.max(1.12,Math.abs(thetaPlus),Math.abs(thetaMinus));
  const imageScale=Math.min(29,imageInset.width*.29/imageExtent,imageInset.height*.29/imageExtent);
  const einsteinRadius=imageScale;
  const imagePlus={x:imageCentre.x+direction.x*thetaPlus*imageScale,y:imageCentre.y+direction.y*thetaPlus*imageScale};
  const imageMinus={x:imageCentre.x+direction.x*thetaMinus*imageScale,y:imageCentre.y+direction.y*thetaMinus*imageScale};
  const imageAngle=Math.atan2(direction.y,direction.x)*180/Math.PI+90;
  const finiteContours=finiteSourceImageContours(sourceOffset);
  const contourPath=points=>points.map((point,index)=>{
    const x=imageCentre.x+point.x*imageScale,y=imageCentre.y+point.y*imageScale;
    return `${index?"L":"M"} ${x.toFixed(2)} ${y.toFixed(2)}`;
  }).join(" ")+" Z";
  const plusContour=contourPath(finiteContours.plus);
  const minusContour=contourPath(finiteContours.minus);
  const finiteSourceImages=`<g data-extended-image="${finiteContours.containsCaustic?"annulus":"arcs"}">
      <path d="${plusContour} ${minusContour}" fill="${sourceColour}" fill-opacity=".24" fill-rule="evenodd" filter="url(#extended-image-glow)"/>
      <path d="${plusContour} ${minusContour}" fill="${sourceColour}" fill-opacity=".22" fill-rule="evenodd"/>
      <path d="${plusContour}" fill="none" stroke="#65d8ff" stroke-width="1.7" opacity=".92"/>
      <path d="${minusContour}" fill="none" stroke="#ffb45e" stroke-width="1.7" opacity=".86"/>
    </g>`;
  const pointRatio=u/FINITE_SOURCE_DISPLAY_RADIUS;
  const pointVisibility=pointRatio*pointRatio/(.08+pointRatio*pointRatio);
  const psfMark=(point,colour,mu,share,label,labelDy)=>{
    const strength=Math.min(1,Math.log1p(mu)/Math.log(32));
    const core=2.3+1.9*strength;
    const major=core*(1.35+1.15*strength),minor=Math.max(1.7,core*.58);
    return `<g data-image="${label}" opacity="${(.45+.53*Math.sqrt(share))*pointVisibility}">
      <ellipse cx="${point.x}" cy="${point.y}" rx="${major+3}" ry="${minor+2}" fill="${colour}" opacity=".22" transform="rotate(${imageAngle} ${point.x} ${point.y})" filter="url(#image-psf)"/>
      <ellipse cx="${point.x}" cy="${point.y}" rx="${major}" ry="${minor}" fill="${colour}" opacity=".42" transform="rotate(${imageAngle} ${point.x} ${point.y})"/>
      <circle cx="${point.x}" cy="${point.y}" r="${core}" fill="${sourceColour}" stroke="${colour}" stroke-width="1.2"/>
      <text x="${point.x+7}" y="${point.y+labelDy}" fill="${colour}" font-size="9" font-family="DM Mono,monospace">${label}</text>
    </g>`;
  };
  const imageMarks=aligned
    ? `${finiteSourceImages}<circle data-einstein-ring="true" cx="${imageCentre.x}" cy="${imageCentre.y}" r="${einsteinRadius}" fill="none" stroke="${sourceColour}" stroke-width="2.4" opacity=".98"/>`
    : `${finiteSourceImages}
       ${psfMark(imagePlus,"#65d8ff",muPlus,sharePlus,"θ+",-6)}
       ${psfMark(imageMinus,"#ffb45e",muMinus,shareMinus,"θ−",11)}`;
  const imageStatus=aligned
    ?"u = 0 · PIERŚCIEŃ EINSTEINA"
    : finiteContours.containsCaustic
      ? w<620?"u ≪ ρvis · NIEMAL PIERŚCIEŃ":`u = ${formatSeparation(u)} · NIEMAL PIERŚCIEŃ`
      : `u = ${formatSeparation(u)} · DWA OBRAZY ROZCIĄGŁE`;
  const sourceCentre={x:sourceInset.x+sourceInset.width*.5,y:sourceInset.y+sourceInset.height*.68};
  const sourceExtent=Math.max(3.15,event.u0+.4);
  const sourceScale=Math.min(15.5,sourceInset.width*.31/3.15,sourceInset.height*.29/sourceExtent);
  const sourceTrackY=sourceCentre.y+sourceOffset.y*sourceScale;
  const sourceMarker={x:sourceCentre.x+sourceOffset.x*sourceScale,y:sourceTrackY};
  const sourceTrackStart=sourceCentre.x-3*sourceScale,sourceTrackEnd=sourceCentre.x+3*sourceScale;
  const impactBracketX=sourceCentre.x+3.18*sourceScale;
  const brightening=Math.min(1,Math.log1p(Math.max(0,amp-1))/Math.log(30));
  const sourceCoreRadius=5.5+1.8*brightening,sourceHaloRadius=14+10*brightening;
  const displayedMass=event.visualLensMass??event.lensMass;
  const massText=displayedMass==null?"MASA NIEUSTALONA":`${event.massStatus==="model"?"≈ ":""}${formatLensMass(displayedMass)}`;
  const atPeak=tau===0;
  const separationMarks=atPeak
    ? `<path d="M ${lensOrigin.x} ${lensOrigin.y} L ${closest.x} ${closest.y}" fill="none" stroke="#f6d48c" stroke-width="1.1" opacity=".72"/>`
    : `<path d="M ${lensOrigin.x} ${lensOrigin.y} L ${closest.x} ${closest.y}" fill="none" stroke="#aeb5bc" stroke-width="1" stroke-dasharray="3 4"/>
       <path d="M ${lensOrigin.x} ${lensOrigin.y} L ${lens.x} ${lens.y}" fill="none" stroke="#f6d48c" stroke-width="1.1" opacity=".72"/>
       <text x="${(lensOrigin.x+closest.x)/2-7}" y="${(lensOrigin.y+closest.y)/2-6}" fill="#aeb5bc" font-size="8" font-family="DM Mono,monospace">u₀</text>
       <text x="${(lensOrigin.x+lens.x)/2+6}" y="${(lensOrigin.y+lens.y)/2-6}" fill="#f6d48c" font-size="8.5" font-family="DM Mono,monospace">u(t)</text>`;
  const closestLabelX=closest.x-68,closestLabelY=closest.y+56;
  const closestValue=atPeak
    ? aligned?"u(t) = u₀ = 0":`u(t) = u₀ = ${formatSeparation(u)}`
    : `u₀ = ${formatSeparation(event.u0)}`;
  const peakMarker=atPeak
    ? `<circle cx="${lens.x}" cy="${lens.y}" r="15" fill="none" stroke="${theme.rim}" stroke-width="1.2" stroke-dasharray="3 4" opacity=".72"/>`
    : "";
  const planeLabel=w<620
    ? ""
    : `<text x="${planeStart.x-6}" y="${planeStart.y-6}" text-anchor="end" fill="#9aa2aa" font-size="8" font-family="DM Mono,monospace">PŁASZCZYZNA SOCZEWKI</text>`;
  const lensInfo=w<620
    ? `<g font-size="8" font-family="DM Mono,monospace"><text x="${lens.x+42}" y="${lens.y+43}" fill="#899198">${theme.text}</text><text x="${lens.x+42}" y="${lens.y+56}" fill="${theme.accent}">${massText}</text></g>`
    : `<g font-size="9" font-family="DM Mono,monospace"><text x="${lens.x+14}" y="${lens.y+23}" fill="#899198">${theme.text}</text><text x="${lens.x+14}" y="${lens.y+37}" fill="${theme.accent}">${massText}</text></g>`;
  const topState=w>720
    ? `<text x="${w*.5}" y="${panelTop+43}" text-anchor="middle" fill="#f3efe6" font-size="17" font-weight="500" font-family="DM Mono,monospace">A = ${formatAmplification(amp)}</text>
       <text x="${w*.5}" y="${panelTop+59}" text-anchor="middle" fill="#7f878e" font-size="8.5" font-family="DM Mono,monospace">u = ${formatSeparation(u)} · τ = ${tau.toFixed(2)}</text>`
    : "";
  const bottomCaption=w>=620
    ? `<text x="${w*.5}" y="${Math.min(axisY+h*.18,h-98)}" text-anchor="middle" fill="#687078" font-size="8" font-family="DM Mono,monospace">RZUT PŁASZCZYZNY NIEBA · SOCZEWKA PORUSZA SIĘ LINIOWO, ŹRÓDŁO I OBSERWATOR SĄ STAŁE</text>`
    : "";
  const planeError=point=>Math.abs((point.x-lens.x)*imageAxis.y-(point.y-lens.y)*imageAxis.x);
  canvas.dataset.u=String(u);canvas.dataset.thetaPlus=String(thetaPlus);canvas.dataset.thetaMinus=String(thetaMinus);
  canvas.dataset.muPlus=String(muPlus);canvas.dataset.muMinus=String(muMinus);canvas.dataset.amplification=String(amp);
  canvas.dataset.tau=String(tau);canvas.dataset.u0=String(event.u0);canvas.dataset.aligned=String(aligned);
  canvas.dataset.lensX=String(lens.x);canvas.dataset.lensY=String(lens.y);
  canvas.dataset.closestX=String(closest.x);canvas.dataset.closestY=String(closest.y);
  canvas.dataset.velocityX=String(trackDir.x*trajectoryScale);canvas.dataset.velocityY=String(trackDir.y*trajectoryScale);
  canvas.dataset.sourceX=String(source.x);canvas.dataset.sourceY=String(source.y);
  canvas.dataset.observerX=String(observer.x);canvas.dataset.observerY=String(observer.y);
  canvas.dataset.alignmentDistancePixels=String(Math.hypot(lens.x-lensOrigin.x,lens.y-lensOrigin.y));
  canvas.dataset.bendPlusPlaneError=String(planeError(bendPlus));canvas.dataset.bendMinusPlaneError=String(planeError(bendMinus));
  canvas.innerHTML=`<title>Geometria mikrosoczewkowania dla ${escapeHtml(event.name)}</title>
    <desc>Model PSPL z liniowym ruchem soczewki. Źródło i obserwator są nieruchome, a promienie załamują się wyłącznie w płaszczyźnie cienkiej soczewki.</desc>
    <defs><radialGradient id="source-glow"><stop offset="0" stop-color="${sourceColour}" stop-opacity="${(.34+.24*brightening).toFixed(2)}"/><stop offset="1" stop-color="${sourceColour}" stop-opacity="0"/></radialGradient>
    <radialGradient id="lens-halo"><stop offset="0" stop-color="${theme.halo}" stop-opacity=".48"/><stop offset="1" stop-color="${theme.halo}" stop-opacity="0"/></radialGradient>
    <filter id="image-psf" x="-100%" y="-100%" width="300%" height="300%"><feGaussianBlur stdDeviation="1.8"/></filter>
    <filter id="extended-image-glow" x="-60%" y="-60%" width="220%" height="220%"><feGaussianBlur stdDeviation="2.2"/></filter>
    <marker id="motion-arrow" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" markerHeight="6" orient="auto"><path d="M 0 0 L 8 4 L 0 8 Z" fill="${theme.rim}" opacity=".75"/></marker></defs>
    <path d="M ${observer.x} ${observer.y} H ${source.x}" fill="none" stroke="rgba(164,184,198,.3)" stroke-width="1" stroke-dasharray="5 6"/>
    <text x="${observer.x}" y="${axisY-12}" fill="#77818a" font-size="8" font-family="DM Mono,monospace">OŚ OPTYCZNA</text>
    <path data-lens-track="true" d="M ${trackStart.x} ${trackStart.y} L ${trackEnd.x} ${trackEnd.y}" fill="none" stroke="${theme.rim}" stroke-opacity=".38" stroke-width="1.2" stroke-dasharray="6 6" marker-end="url(#motion-arrow)"/>
    <text x="${trackStart.x-4}" y="${trackStart.y-9}" fill="${theme.rim}" font-size="8" font-family="DM Mono,monospace">STAŁY KIERUNEK RUCHU</text>
    ${separationMarks}
    <g data-alignment-origin="true">
      <circle cx="${lensOrigin.x}" cy="${lensOrigin.y}" r="5.2" fill="#0a0d11" stroke="#e8eef4" stroke-width="1.1"/>
      <path d="M ${lensOrigin.x-8} ${lensOrigin.y} H ${lensOrigin.x+8} M ${lensOrigin.x} ${lensOrigin.y-8} V ${lensOrigin.y+8}" stroke="#e8eef4" stroke-width=".8" opacity=".7"/>
      <text x="${lensOrigin.x+10}" y="${lensOrigin.y-10}" fill="#c8d0d7" font-size="8" font-family="DM Mono,monospace">JEDYNY PUNKT β = 0</text>
    </g>
    <circle cx="${closest.x}" cy="${closest.y}" r="4.2" fill="#0a0d11" stroke="${theme.rim}" stroke-width="1.3"/>
    <path d="M ${closest.x-5} ${closest.y+7} L ${closestLabelX+30} ${closestLabelY-15}" fill="none" stroke="#aeb5bc" stroke-width=".8" opacity=".55"/>
    <text x="${closestLabelX}" y="${closestLabelY}" text-anchor="middle" fill="#aeb5bc" font-size="8" font-family="DM Mono,monospace">NAJMNIEJSZE ZBLIŻENIE · τ = 0</text>
    <text x="${closestLabelX}" y="${closestLabelY+13}" text-anchor="middle" fill="#f6d48c" font-size="8" font-family="DM Mono,monospace">${closestValue}</text>
    <path d="M ${planeStart.x} ${planeStart.y} L ${planeEnd.x} ${planeEnd.y}" fill="none" stroke="rgba(255,255,255,.3)" stroke-width="1" stroke-dasharray="4 5"/>
    ${planeLabel}
    <path data-ray="plus" d="M ${source.x} ${source.y} L ${bendPlus.x} ${bendPlus.y} L ${observer.x} ${observer.y}" fill="none" stroke="#65d8ff" stroke-width="${rayPlusWidth}" opacity="${rayPlusOpacity}" stroke-linejoin="round"/>
    <path data-ray="minus" d="M ${source.x} ${source.y} L ${bendMinus.x} ${bendMinus.y} L ${observer.x} ${observer.y}" fill="none" stroke="#ffb45e" stroke-width="${rayMinusWidth}" opacity="${rayMinusOpacity}" stroke-linejoin="round"/>
    <circle cx="${bendPlus.x}" cy="${bendPlus.y}" r="4.2" fill="#65d8ff" stroke="#071016" stroke-width="1.5"/>
    <circle cx="${bendMinus.x}" cy="${bendMinus.y}" r="4.2" fill="#ffb45e" stroke="#160f08" stroke-width="1.5"/>
    <text x="${bendPlus.x+8}" y="${bendPlus.y-7}" fill="#65d8ff" font-size="9" font-family="DM Mono,monospace">θ+</text>
    <text x="${bendMinus.x+8}" y="${bendMinus.y+13}" fill="#ffb45e" font-size="9" font-family="DM Mono,monospace">θ−</text>
    <circle cx="${observer.x}" cy="${observer.y}" r="8" fill="#e8eef4" opacity=".12"/><circle cx="${observer.x}" cy="${observer.y}" r="4.8" fill="#e8eef4"/>
    <circle cx="${lens.x}" cy="${lens.y}" r="20" fill="url(#lens-halo)"/>
    <circle cx="${lens.x}" cy="${lens.y}" r="10" fill="${theme.body}" stroke="${theme.rim}" stroke-width="2"/>
    ${peakMarker}
    <circle cx="${source.x}" cy="${source.y}" r="${sourceHaloRadius}" fill="url(#source-glow)"/><circle cx="${source.x}" cy="${source.y}" r="${sourceCoreRadius}" fill="${sourceColour}"/>
    <g fill="#899198" font-size="9" font-family="DM Mono,monospace"><text x="${observer.x-28}" y="${observer.y+25}">OBSERWATOR STAŁY</text><text x="${source.x-36}" y="${source.y-16}">ŹRÓDŁO STAŁE</text><text x="${source.x-80}" y="${source.y+24}" fill="${sourceColour}">A(t) = ${formatAmplification(amp)}</text></g>
    ${lensInfo}
    <rect x="${imageInset.x}" y="${imageInset.y}" width="${imageInset.width}" height="${imageInset.height}" rx="12" fill="rgba(5,7,10,.74)" stroke="rgba(255,255,255,.14)"/>
    <path d="M ${imageInset.x+14} ${imageCentre.y} H ${imageInset.x+imageInset.width-14} M ${imageCentre.x} ${imageInset.y+45} V ${imageInset.y+imageInset.height-10}" fill="none" stroke="rgba(255,255,255,.12)"/>
    <circle cx="${imageCentre.x}" cy="${imageCentre.y}" r="${einsteinRadius}" fill="none" stroke="#65d8ff" stroke-width="1" stroke-dasharray="3 4" opacity=".5"/>
    <circle cx="${imageCentre.x}" cy="${imageCentre.y}" r="3.2" fill="${theme.body}" stroke="${theme.rim}" stroke-width="1"/>
    ${imageMarks}
    <text x="${imageCentre.x+einsteinRadius+4}" y="${imageCentre.y-4}" fill="#65d8ff" font-size="7.5" font-family="DM Mono,monospace">θE</text>
    <text x="${imageInset.x+16}" y="${imageInset.y+22}" fill="#f3efe6" font-size="9" font-family="DM Mono,monospace">PŁASZCZYZNA OBRAZU</text>
    <text x="${imageInset.x+16}" y="${imageInset.y+39}" fill="#a5acb3" font-size="8" font-family="DM Mono,monospace">${imageStatus}</text>
    <text x="${imageInset.x+imageInset.width-12}" y="${imageInset.y+22}" text-anchor="end" fill="#687078" font-size="7" font-family="DM Mono,monospace">ρvis = 0,05 θE</text>
    <rect x="${sourceInset.x}" y="${sourceInset.y}" width="${sourceInset.width}" height="${sourceInset.height}" rx="12" fill="rgba(5,7,10,.74)" stroke="rgba(255,255,255,.14)"/>
    <path d="M ${sourceInset.x+14} ${sourceCentre.y} H ${sourceInset.x+sourceInset.width-14} M ${sourceCentre.x} ${sourceInset.y+45} V ${sourceInset.y+sourceInset.height-10}" fill="none" stroke="rgba(255,255,255,.12)"/>
    <path d="M ${sourceTrackEnd} ${sourceTrackY} H ${sourceTrackStart}" fill="none" stroke="rgba(188,231,255,.48)" stroke-dasharray="6 5" marker-end="url(#motion-arrow)"/>
    <path d="M ${sourceCentre.x} ${sourceCentre.y} L ${sourceMarker.x} ${sourceMarker.y}" fill="none" stroke="#f6d48c" stroke-width="1.2"/>
    <path d="M ${impactBracketX-4} ${sourceCentre.y} h 8 M ${impactBracketX} ${sourceCentre.y} V ${sourceTrackY} M ${impactBracketX-4} ${sourceTrackY} h 8" fill="none" stroke="#aeb5bc"/>
    <circle cx="${sourceCentre.x}" cy="${sourceCentre.y}" r="3.8" fill="#ff6b8f"/>
    <circle cx="${sourceMarker.x}" cy="${sourceMarker.y}" r="5.4" fill="${sourceColour}"/>
    <text x="${sourceMarker.x+7}" y="${sourceMarker.y-6}" fill="${sourceColour}" font-size="8.5" font-family="DM Mono,monospace">ŹRÓDŁO</text>
    <text x="${(sourceCentre.x+sourceMarker.x)/2-8}" y="${(sourceCentre.y+sourceMarker.y)/2-5}" text-anchor="end" fill="#f6d48c" font-size="8.5" font-family="DM Mono,monospace">β = u θE</text>
    <text x="${impactBracketX-7}" y="${(sourceCentre.y+sourceTrackY)/2+3}" text-anchor="end" fill="#aeb5bc" font-size="8" font-family="DM Mono,monospace">u₀</text>
    <text x="${sourceInset.x+16}" y="${sourceInset.y+22}" fill="#f3efe6" font-size="9" font-family="DM Mono,monospace">PŁASZCZYZNA ŹRÓDŁA</text>
    <text x="${sourceInset.x+16}" y="${sourceInset.y+39}" fill="#ff7b9a" font-size="8.5" font-family="DM Mono,monospace">KAUSTYKA PUNKTOWA β = 0</text>
    ${topState}
    ${bottomCaption}`;
}

window.addEventListener("resize",()=>{fitMap(true);if(state.selected)updateSimulation();});
window.addEventListener("keydown",event=>{
  if(event.key==="/"&&document.activeElement!==$("#search")){event.preventDefault();$("#search").focus();}
  if(event.key==="Escape"&&$("#detail").open)closeDetail();
  if((event.key==="+"||event.key==="=")&&!$("#detail").open)zoomAt(1.4,viewport.clientWidth/2,viewport.clientHeight/2);
  if(event.key==="-"&&!$("#detail").open)zoomAt(1/1.4,viewport.clientWidth/2,viewport.clientHeight/2);
  if(event.key==="0"&&!$("#detail").open)fitMap();
});

async function init() {
  const loading=$("#loading");
  loading.classList.remove("hidden","error");
  $(".load-title").textContent="Ładowanie atlasu zdarzeń";
  $("#load-message").textContent="";
  try {
    const response=await fetch("/api/events");if(!response.ok)throw new Error(await response.text());
    const payload=await response.json();state.events=payload.events;state.meta=payload.meta;
    state.events.forEach(event=>{
      event.searchId=String(event.sourceId).toLowerCase();
      event.searchName=String(event.name).replace(/[–—]/g,"-").toLowerCase();
    });
    const requestedFilter=new URL(location.href).searchParams.get("filter");
    if(["all","strong","short","long","catalog-mass","model-mass"].includes(requestedFilter))state.filter=requestedFilter;
    $$(".filter").forEach(button=>{
      const active=button.dataset.filter===state.filter;
      button.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active));
    });
    $("#total-count").textContent=state.events.length;createMarkers();fitMap(true);
    const filteredSummary=state.meta.filteredOutCount
      ? `Odrzucono ${state.meta.filteredOutCount} rekordów podczas walidacji.`
      : "Wszystkie rekordy przeszły walidację.";
    $(".count").setAttribute("aria-label",`${state.events.length} zdarzeń. ${filteredSummary}`);
    $(".count").title=filteredSummary;
    const hash=normalizeId(location.hash.slice(1));const event=state.events.find(item=>normalizeId(item.name)===hash);if(event)openDetail(event);
    const sky=$("#sky");
    if(!sky.complete)await new Promise((resolve,reject)=>{
      sky.addEventListener("load",resolve,{once:true});
      sky.addEventListener("error",()=>reject(new Error("Nie udało się wczytać obrazu mapy nieba.")),{once:true});
    });
    if(!sky.naturalWidth)throw new Error("Obraz mapy nieba jest niedostępny lub uszkodzony.");
    loading.classList.add("hidden");
  } catch(error) {
    loading.classList.add("error");
    $(".load-title").textContent="Nie udało się uruchomić mapy";
    $("#load-message").textContent=error instanceof Error?error.message:"Nieznany błąd ładowania.";
    $(".load-line").style.background="#ff5e84";
    console.error(error);
  }
}
$("#retry-load").addEventListener("click",init);
init();
</script>
</body>
</html>
"""


FAVICON = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
<rect width="64" height="64" rx="12" fill="#080a0d"/>
<ellipse cx="32" cy="32" rx="10" ry="26" fill="none" stroke="#ffb45e" stroke-width="3" transform="rotate(28 32 32)"/>
<ellipse cx="32" cy="32" rx="26" ry="10" fill="none" stroke="#65d8ff" stroke-width="3" transform="rotate(-28 32 32)"/>
<circle cx="32" cy="32" r="4" fill="white"/>
</svg>"""


def _range_from_header(header, size):
    if not header:
        return None
    if not header.startswith("bytes=") or "," in header:
        raise ValueError("Unsupported byte range")
    try:
        start_text, end_text = header[6:].split("-", 1)
        if start_text:
            start = int(start_text)
            end = int(end_text) if end_text else size - 1
        else:
            length = int(end_text)
            if length <= 0:
                raise ValueError("Invalid suffix length")
            start = max(0, size - length)
            end = size - 1
        if start < 0 or end < start or start >= size:
            raise ValueError("Byte range outside resource")
        return start, min(end, size - 1)
    except (TypeError, ValueError) as error:
        raise ValueError("Invalid byte range") from error


def create_handler(payload_bytes, sky_map_path):
    html_bytes = APP_HTML.encode("utf-8")
    favicon_bytes = FAVICON.encode("utf-8")
    compressed_payload = gzip.compress(payload_bytes, compresslevel=6)
    compressed_html = gzip.compress(html_bytes, compresslevel=6)
    payload_etag = f'"{hashlib.sha256(payload_bytes).hexdigest()[:24]}"'
    html_etag = f'"{hashlib.sha256(html_bytes).hexdigest()[:24]}"'
    sky_stat = sky_map_path.stat()
    sky_etag = f'"{sky_stat.st_size:x}-{sky_stat.st_mtime_ns:x}"'

    class AuroraHandler(BaseHTTPRequestHandler):
        server_version = "AURORA/1.0"

        def log_message(self, format_string, *args):
            if getattr(self.server, "verbose", False):
                super().log_message(format_string, *args)

        def _security_headers(self):
            self.send_header("X-Content-Type-Options", "nosniff")
            self.send_header("X-Frame-Options", "DENY")
            self.send_header("Referrer-Policy", "no-referrer")
            self.send_header("Cross-Origin-Resource-Policy", "same-origin")
            self.send_header(
                "Content-Security-Policy",
                "default-src 'self'; script-src 'self' 'unsafe-inline'; "
                "style-src 'self' 'unsafe-inline'; img-src 'self' data:; "
                "connect-src 'self'; object-src 'none'; base-uri 'none'; "
                "frame-ancestors 'none'",
            )

        def _send_bytes(
            self,
            content,
            content_type,
            cache="no-store",
            *,
            etag=None,
            compressed=None,
        ):
            if etag and self.headers.get("If-None-Match") == etag:
                self.send_response(HTTPStatus.NOT_MODIFIED)
                self.send_header("ETag", etag)
                self.send_header("Cache-Control", cache)
                self._security_headers()
                self.end_headers()
                return
            use_gzip = (
                compressed is not None
                and "gzip" in self.headers.get("Accept-Encoding", "").lower()
            )
            body = compressed if use_gzip else content
            self.send_response(HTTPStatus.OK)
            self.send_header("Content-Type", content_type)
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", cache)
            if etag:
                self.send_header("ETag", etag)
            if compressed is not None:
                self.send_header("Vary", "Accept-Encoding")
            if use_gzip:
                self.send_header("Content-Encoding", "gzip")
            self._security_headers()
            self.end_headers()
            if self.command != "HEAD":
                try:
                    self.wfile.write(body)
                except (BrokenPipeError, ConnectionResetError):
                    return

        def _send_sky_map(self):
            size = sky_map_path.stat().st_size
            try:
                byte_range = _range_from_header(self.headers.get("Range"), size)
            except ValueError:
                self.send_response(HTTPStatus.REQUESTED_RANGE_NOT_SATISFIABLE)
                self.send_header("Content-Range", f"bytes */{size}")
                self.send_header("Content-Length", "0")
                self._security_headers()
                self.end_headers()
                return
            if not byte_range and self.headers.get("If-None-Match") == sky_etag:
                self.send_response(HTTPStatus.NOT_MODIFIED)
                self.send_header("ETag", sky_etag)
                self.send_header("Cache-Control", "public, max-age=3600")
                self._security_headers()
                self.end_headers()
                return
            start, end = byte_range if byte_range else (0, size - 1)
            status = HTTPStatus.PARTIAL_CONTENT if byte_range else HTTPStatus.OK
            self.send_response(status)
            self.send_header("Content-Type", mimetypes.guess_type(sky_map_path.name)[0] or "image/png")
            self.send_header("Content-Length", str(end - start + 1))
            self.send_header("Accept-Ranges", "bytes")
            self.send_header("Cache-Control", "public, max-age=3600")
            self.send_header("ETag", sky_etag)
            if byte_range:
                self.send_header("Content-Range", f"bytes {start}-{end}/{size}")
            self._security_headers()
            self.end_headers()
            if self.command == "HEAD":
                return
            with sky_map_path.open("rb") as file:
                file.seek(start)
                remaining = end - start + 1
                while remaining:
                    MEMORY.throttle()
                    chunk = file.read(min(1024 * 1024, remaining))
                    if not chunk:
                        break
                    try:
                        self.wfile.write(chunk)
                    except (BrokenPipeError, ConnectionResetError):
                        return
                    remaining -= len(chunk)

        def do_GET(self):
            path = unquote(urlsplit(self.path).path)
            if path == "/":
                self._send_bytes(
                    html_bytes,
                    "text/html; charset=utf-8",
                    "no-cache",
                    etag=html_etag,
                    compressed=compressed_html,
                )
            elif path == "/api/events":
                self._send_bytes(
                    payload_bytes,
                    "application/json; charset=utf-8",
                    "private, max-age=60",
                    etag=payload_etag,
                    compressed=compressed_payload,
                )
            elif path == "/sky-map":
                self._send_sky_map()
            elif path == "/favicon.svg":
                self._send_bytes(favicon_bytes, "image/svg+xml", "public, max-age=86400")
            else:
                self.send_error(HTTPStatus.NOT_FOUND, "Not found")

        do_HEAD = do_GET

    return AuroraHandler


def parse_args():
    parser = argparse.ArgumentParser(
        description="Interactive AURORA map of Gaia DR3 microlensing events.",
    )
    parser.add_argument(
        "--catalog",
        type=Path,
        default=DEFAULT_CATALOG,
        help="Input FITS catalogue",
    )
    parser.add_argument(
        "--map",
        dest="sky_map",
        type=Path,
        help="Hammer PNG from aurora_sky_render.py",
    )
    parser.add_argument(
        "--host",
        default=DEFAULT_SERVER_HOST,
        help="Local server address",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=DEFAULT_SERVER_PORT,
        help="Port; 0 chooses a free port",
    )
    parser.add_argument(
        "--no-browser",
        action="store_true",
        help="Do not open the browser automatically",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print HTTP request logs",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    MEMORY.throttle()
    catalog_path = args.catalog.expanduser().resolve()
    if not catalog_path.is_file():
        raise FileNotFoundError(f"Microlensing catalogue does not exist: {catalog_path}")
    sky_map_path = find_sky_map(args.sky_map)

    console.print("\n[AURORA] Interactive microlensing atlas")
    console.print("─" * 45)
    MEMORY.throttle()
    payload = load_event_payload(catalog_path)
    payload_bytes = json.dumps(
        payload,
        ensure_ascii=False,
        separators=(",", ":"),
    ).encode("utf-8")
    console.print(f"  ✓ Sky background: {sky_map_path}")

    server = ThreadingHTTPServer(
        (args.host, args.port),
        create_handler(payload_bytes, sky_map_path),
    )
    server.verbose = args.verbose
    browser_host = (
        "127.0.0.1"
        if args.host == "0.0.0.0"
        else "[::1]"
        if args.host == "::"
        else f"[{args.host}]"
        if ":" in args.host and not args.host.startswith("[")
        else args.host
    )
    url = f"http://{browser_host}:{server.server_address[1]}/"
    console.print(f"  ✓ Atlas ready: {url}")
    console.print("  → Press Ctrl+C to stop")

    if not args.no_browser:
        timer = threading.Timer(0.35, webbrowser.open, args=(url,))
        timer.daemon = True
        timer.start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        console.print("\n  ✓ Atlas stopped")
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
